### ISSUE TITLE
Use enums for Task.state

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#10]
It seems that Task.state is just storing string constants, so maybe it would be good to use an enum instead?

**Comment by dabeaz** [comment]
I'd thought about enums, but since the state is purely informational, I decided a string would probably be fine (resisting the urge to add extra complexity to the implementation).   If the state becomes used for other things in the future, I'd be open to revisiting a enum representation though.

**Comment by brettcannon** [comment]
Plus the str and repr of enums is still very readable so there isn't any loss in debugging abilities. I figured since the set of possible values is extremely finite it made sense to know what those possible values are by documenting them in an enum rather than having to search the code for all possible states.
