### ISSUE TITLE
spawn hanging in master when using list comprehensions (?!)

### ISSUE THREAD

**Issue by aktiur** [dabeaz/curio#102]
Hello all,

I was playing with Curio using the master branch version and trying to write a small chat server to understand the concepts when I came across what looks like a weird bug.

### Curio and Python version
master (0e2a274d27784fa641f3aa3adda9a4a75b8b1436)

```
>>> print(sys.version)
3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609]
```
### Code used
The full code I used is there https://gist.github.com/aktiur/169fa7a3c86501f6ec380c353c6642bd
But here is the relevant part:
```python
async def spawn_and_wait_all(coros):
    tasks = []
    for coro in coros:
        task = await curio.spawn(coro)
        tasks.append(task)
    for task in tasks:
        await task.join()

async def sendall(content):
    coros = [queue.put(content) for queue in queues]
    await spawn_and_wait_all(coros)
```

### Bug summary
When `sendall` is awaited, if `queues` is not empty, the task will hang with 100 % cpu load. The monitor reports the following information:

```
curio > ps
Task   State        Cycles     Timeout Task                                               
------ ------------ ---------- ------- --------------------------------------------------
0      READ_WAIT    1          None    Kernel.run.<locals>._kernel_task                  
1      FUTURE_WAIT  2          None    Monitor.monitor_task                              
4      RUNNING      5          None    _run_server.<locals>.run_client                   
5      QUEUE_GET    3          None    _client_writer                                    
7      RUNNING      735641     None    Kernel.run.<locals>._shutdown_tasks               
curio > where 4
Stack for Task(id=4, <coroutine object _run_server.<locals>.run_client at 0x7fd9b8727678>, state='RUNNING') (most recent call last):
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/network.py", line 82, in run_client
    await client_connected_task(client, addr)
  File "chat_server.py", line 32, in client_reader
    await sendall(name + b": " + line)
  File "chat_server.py", line 18, in sendall
    await spawn_and_wait_all(coros)
  File "chat_server.py", line 11, in spawn_and_wait_all
    task = await curio.spawn(coro)
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/task.py", line 137, in spawn
    return await _spawn(coro, daemon)
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/traps.py", line 85, in _spawn
    return (yield _trap_spawn, coro, daemon)

curio > where 7
Stack for Task(id=7, <coroutine object Kernel.run.<locals>._shutdown_tasks at 0x7fd9b8727b48>, state='RUNNING') (most recent call last):
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/kernel.py", line 320, in _shutdown_tasks
    await task.cancel()
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/task.py", line 81, in cancel
    result = await self.cancel_no_wait()
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/task.py", line 95, in cancel_no_wait
    await _cancel_task(self)
  File "/home/arthur/.envs/curio-essays/lib/python3.5/site-packages/curio/traps.py", line 95, in _cancel_task
    yield (_trap_cancel_task, task)
```

### Steps to reproduce
To reproduce the bug, one could follow the following steps using the code in the gist:

* Start the server
* Connect with another terminal using nc or telnet
* Send one line of text to register one's name (my code assumes the first line received is one's display name)
* Send any line of content

### Other information
This bug does not occur if I replace the list comprehension in `sendall` with an explicit for loop:
```python
async def sendall(content):
    coros = []
    for queue in queues:
        coros.append(queue.put(content))
    await spawn_and_wait_all(coros)
```
It also does not occur using curio 0.5 from pip.

I'm not familiar enough with Curio's internals (or even with list comprehensions' semantics) to diagnose what's happening, but if it's really a bug of Curio, I'd be willing to investigate more thoroughly as long as I get some pointers from more knowledgeable folks.

**Comment by dabeaz** [comment]
Oh, interesting.  I know what this is (and it perfectly reflects the reason why curio is "experimental" ;-).  For now, don't use a list comprehension.  Will have a fix in the next day.

**Comment by aktiur** [comment]
I'd be very curious to know what's happening, if you have the time to
elaborate! This still looks like dark magic to me :o

Le vendredi 11 novembre 2016, David Beazley <notifications@github.com> a
écrit :

**Comment by dabeaz** [comment]
This is being caused by a bug in the dark magic of a dark corner of experimental curio metaprogramming.   Given the experimental nature of the project and to satisfy my curiosity about where it might lead (against my better judgement), I've pushed a patch that should fix this.  Let me know.

**Comment by aktiur** [comment]
Ok, I think I can see what you're doing. Let me know if I understand you
correctly or not.

Basically, you want some asynchronous functions (including queue.put) to
have a synchronous version that can be called with the same name and
signature (without the await) and you added the @awaitable decorator for
this reason.

To determine which version is being called, you basically looked at the
call stack to see if the calling function was async or not... which was
failing when a comprehension was used in an async context.

To fix that, you factored out that looking at the call stack in a function
that calls itself recursively higher on the stack whenever it notices the
calling context is a comprehension.

The only thing I don't understand is why _is_coroutine calls itself with
level+2 (instead of level+1). I would have said level+1 is the function
into which the comprehension is nested, and level+2 the function that
called it. What am I missing?

Le vendredi 11 novembre 2016, David Beazley <notifications@github.com> a
écrit :

**Comment by dabeaz** [comment]
The level+2 reflects the extra stack frame of the recursive call plus the extra stack frame of going up one level.

Honestly, this code is kind of insane.   I'm not sure I'll keep it.  That said, part of curio involves exploring the space of what's possible with async/await.  Since it's a new Python feature that isn't well understood, I think it's okay to fool around with crazy stuff like this for now. ;-).

**Comment by njsmith** [comment]
*twitch*

**Comment by aktiur** [comment]
> The level+2 reflects the extra stack frame of the recursive call plus the extra stack frame of going up one level.

Ok that makes sense, I had missed the extra frame for the recursive call. I feel better, I thought I was actually missing something fundamental about the semantics of list comprehension in Python.

Anyway, my original code now works. Thank you!
