### ISSUE TITLE
Monitor client prevents the monitor thread termination

### ISSUE THREAD

**Issue by ZhukovAlexander** [dabeaz/curio#108]
Currently, a monitoring thread won't exit until a client asks it to do so. The issue is [partially addressed here](https://github.com/dabeaz/curio/pull/107), but this patch only handles the case when there is no active client connection. 

Although introducing timeouts can prevent the [interactive_loop](https://github.com/dabeaz/curio/blob/master/curio/monitor.py#L151) from blocking indefinitely, this solution doesn't work due to [https://bugs.python.org/issue7322](https://bugs.python.org/issue7322)

**Comment by dabeaz** [comment]
Fixed it using a generator.  I mean, what else would I use? ;-)

**Comment by xgid** [comment]
Hi all and have a challenging new year! ;-)

I'm a close follower of your amazing work in Curio. Congratulations!

Reviewing your recent commit, I've come across some minor doubts. In [this code](https://github.com/dabeaz/curio/blob/c6f662a1f57107024935a77a8458d61874e463ed/curio/monitor.py#L203-L209):
```python
            resp = next(input_lines, None)
            if not resp:
                return
            try:
                if not resp or resp.startswith('q'):
                    self.command_exit(sout)
                    return
```

- Should `self.command_exit(sout)` be called also after `if not resp:` and before `return`?
- May `if not resp` be removed from the second `if` as redundant?

They are probably irrelevant, but if they may be of any help...
