### ISSUE TITLE
Can't import curio

### ISSUE THREAD

**Issue by Endle** [dabeaz/curio#11]
My code:
```Python
# show.py
import curio
if __name__ == '__main__':
    kernel = curio.Kernel()
```
And I failed to run it
> $ python3 show.py
> Traceback (most recent call last):
>   File "show.py", line 2, in <module>
>     import curio
>   File "/usr/lib/python3.4/site-packages/curio/__init__.py", line 5, in <module>
>     from .kernel import *
>   File "/usr/lib/python3.4/site-packages/curio/kernel.py", line 79
>     async def join(self, *, timeout=None):
>             ^
> SyntaxError: invalid syntax

My Environment:

> $ pip freeze
> //---snip---
> curio==0.1

> $ python3
> Python 3.4.3 (default, Jun 29 2015, 12:16:01) 
> [GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux

Anyone has ideas on it? Thank you

**Comment by nchammas** [comment]
Curio requires Python 3.5+. You are running Python 3.4.3.

**Comment by Endle** [comment]
Thanks. I misunderstood the doc
