### ISSUE TITLE
Need an efficient way to communicate between curio tasks and other threads

### ISSUE THREAD

**Issue by njsmith** [dabeaz/curio#119]
Following up on some discussion in #111:

A standard feature in event loops is some sort of `call_soon_threadsafe` call, which allows code running in another thread to schedule a callback onto the event loop. This is then used as a primitive to build various sorts of communication mechanisms between code running in the event loop and code running in the thread. The standard way of implementing this involves using a wake-up pipe as a safe cross-thread notification mechanism.

For curio, we also need to be able do this kind of communication, though it probably makes more sense to have some sort of queue instead of a `call_soon` API, because `call_soon` is a [task-spawning API, and curio tries to avoid task-spawning APIs](https://vorpus.org/blog/some-thoughts-on-asynchronous-api-design-in-a-post-asyncawait-world/#c-c-c-c-causality-breaker).

Right now, the way to do this is to use a regular `queue.Queue`, and on the curio side access it via `await run_in_thread(queue.Queue.get)` (or the equivalent sugar: `abide(queue.Queue.get)`). Under the hood, `run_in_thread` relies on the `future_wait` trap to detect when the `get` has finished, and `future_wait` uses a wake-up pipe mechanism.

So that's all fine, but it's inefficient: every task that wants to communicate with a worker thread has to commit a whole extra thread just to sitting around waiting for the `queue.Queue`'s internal `threading.Condition` variable to get signaled. If we use `run_in_thread`/`abide`, then these threads all live in the same fixed-size thread pool, so we might even starve out other users of `run_in_thread` or get deadlocks. (E.g. if our thread pool has N threads, and we spawn N workers, and each worker needs to send back a message, and each message needs a thread, then we need 2*N threads total, and if all the workers fill up the thread pool and then block waiting for messages to be sent and responded to, then the whole thing will deadlock.)

The solution is to provide some more direct exposure of the underlying wake-a-task-from-another-thread primitive, which could be used to build a `Queue` that can communicate between curio tasks and other threads without using the thread pool.

**Comment by dabeaz** [comment]
I'm not adding a special `call_soon()` API to curio.   The kernel presently has the ability to wait on a `Future` so if some kind of coordination with threads is needed, it should be built on that.  

As for N curio tasks communicating with N threads and deadlock---don't do that! ;-)   The `abide()` mechanism will likely work just fine if you are doing something like communicating from a single thread to a single curio task though.  For example, communicating between Tkinter and curio.  

I'm open to new kinds of communication mechanisms if someone wants to implement something though.   There are probably some efficiencies that can be had if one makes assumptions about the endpoints of a queue.   For example, a queue that can only be read by threads and written by curio (and the other way around).

**Comment by dabeaz** [comment]
Just thinking out loud about this N threads and N workers thing.    I wonder if you could make something like that work more sanely if you used a dedicated task to serve as an intermediary.  For example::

    thr_q = threading.Queue()
    cur_q = curio.Queue()

    async def bridge(thr_q, cur_q):
        while True:
             curio.abide(thr_q.put(await cur_q.get()))

Now, if you had a thousand curio tasks running and they wanted to communicate with the thread, they'd just put their items onto `cur_q`.   The `bridge()` task would take them and hand it over to the thread.   Only one thread would be needed.

Not suggesting that this would be the "solution" to efficient Curio-Thread communication ;-).  It just seemed like an interesting approach that would greatly reduce the number of background threads needed to have N worker tasks put things on a thread-queue using existing machinery.

**Comment by nameoftherose** [comment]
Thank you all. I now see why it is not a good idea to start a coroutine from a synchronous function.
Should I close this or should the owner close it?

**Comment by ZhukovAlexander** [comment]
@dabeaz , in your last example shouldn't it be ```await curio.abide(thr_q.put, await cur_q.get())```?

**Comment by dabeaz** [comment]
Yes. Missing an "await".  I'll edit (good catch!)

**Comment by dabeaz** [comment]
Have made a lot of improvements related to thread-task interaction over the last few months.   Maybe try a UniversalQueue which greatly reduces the number of threads required. Closing this issue.
