### ISSUE TITLE
Additional asterisk in new_task function definition

### ISSUE THREAD

**Issue by andyxning** [dabeaz/curio#12]
currently the definition of `new_task` is like below. However, i don't know how does the second parameter, the asterisk, means.  

    async def new_task(coro, *, daemon=False):
    '''
    Create a new task.
    '''
        return await _new_task(coro, daemon)

In fact, if we call the `new_task` function with an `additional_useless_argument`, just like below:

    # hello.py
    import curio

    async def countdown(n):
        while n > 0:
            print('T-minus', n)
            await curio.sleep(1)
            n -= 1

    if __name__ == '__main__':
        kernel = curio.Kernel()
        additional_useless_argument = 0
        kernel.run(countdown(10), additional_useless_argument)

error message is shown:  
    
    TypeError: new_task() takes 1 positional argument but 2 were given

**Comment by dabeaz** [comment]
The daemon argument to new_task() is used to create a daemonic task.  It must be specified by keyword only and can only be used inside a coroutine (which is not evident in the code example on this issue).

**Comment by andyxning** [comment]
@dabeaz I know the `daemon` parameter must be specified by a keyword argument. What confused me is the use of the second parameter, i.e. `*` the asterisk char.

**Comment by dabeaz** [comment]
The * forces it to be keyword.  Keyword-only arguments.

**Comment by andyxning** [comment]
Ok, i got it.
