### ISSUE TITLE
Allow for `pickle.HIGHEST_PROTOCOL`

### ISSUE THREAD

**Issue by jkbbwr** [dabeaz/curio#130]
Allow either by config or convention `pickle.HIGHEST_PROTOCOL` to be set when pickling.
It gives better speed at the cost of backwards compatibility

**Comment by njsmith** [comment]
I assume you're talking about in curio.channel.Channel.send? It should just be set unconditionally -- there's no backwards compatibility concern when talking between two processes on the same machine.

**Comment by dabeaz** [comment]
Good catch.  We should make sure Curio uses the most efficient protocol possible.

**Comment by dabeaz** [comment]
Fixed.
