### ISSUE TITLE
Piping

### ISSUE THREAD

**Issue by imrn** [dabeaz/curio#132]
Following piped shell command example dumps html formatted man page:

`zcat /usr/share/man/man1/man.1.gz | groff -mandoc -Thtml -P -l -P -D -P /tmp/`

Equivalent Curio code is as follows. Are there any
suggestions or any possible Curio goodies for "PIPING
the output of one process into another" easily? Thanks..

```python
async def dumpstream(instream, outstream):
    async with outstream:
        async with instream:
            while True:
                rd = await instream.read()
                if not rd:
                    break
                await outstream.write(rd)

groffcmd = 'groff -mandoc -Thtml -P -l -P -D -P /tmp/'.split()
zcatcmd = 'zcat /usr/share/man/man1/man.1.gz'.split()

groff = Popen(groffcmd, stdin=PIPE, stdout=PIPE)
zcat = Popen(zcatcmd, stdout=PIPE)

await spawn(dumpstream(zcat.stdout, groff.stdin))

while True:
    rd = await groff.stdout.read()
    if not rd:
        break
    await DumpIntoHttpResp(rd)

# Or alternatively this: (HttpResponse may be a stream.)
await dumpstream(groff.stdout, httpresp)
```

**Comment by dabeaz** [comment]
Not a bad idea to have some extra utilities for this.

**Comment by imrn** [comment]
The trick is having a 'seperate' helper task for reading from proc1
and writing to proc2. I was unable to provide proper piping functionality
with just linear code. But I'd like to hear from anyone with a better idea.

Another issue is about the semantic construct Curio would provide
for this functionality. I currently have no suggestion. But there
is an interesting discussion here:

http://stackoverflow.com/questions/1586850/why-dont-i-see-pipe-operators-in-most-high-level-languages

**Comment by dabeaz** [comment]
The closest thing to this in Curio would be the implementation of the `communicate()` method in `curio.subprocess`.   It uses multiple tasks.

**Comment by imrn** [comment]
If "helper task(s)" is the only way, then the question on the
stackoverflow is answered: You need asyncs for this.
Or a helper thread may help. But this may be reason
mainstreams stayed away from it.

This may be interesting find of the day: It means
piping is intrinsically in the land of Curio..

**Comment by dabeaz** [comment]
Maybe.  One of the things that really blew my mind with curio was the fact that I could just do some things like this:

    stdout_task = await spawn(p.stdout.readall())
    stderr_task = await spawn(p.stderr.readall())
    stdout = await stdout_task.join()
    stderr = await stderr_task.join()

And there it is---all of the output from both stdout/stderr on some process.   I'll bet there are some pretty interesting things that could be done if someone wanted to take this to the next level.

**Comment by imrn** [comment]
What about this:

```python
groff = Popen(groffcmd, stdin=PIPE, stdout=PIPE)
zcat = Popen(zcatcmd, outstream=groff.stdin, stdout=PIPE) 
# creates helper task behind the scenes.  But changes Popen api :(

# or 

groff = Popen(groffcmd, stdin=PIPE, stdout=PIPE)
zcat = Popen(zcatcmd, stdout=PIPE)
await pipe(instream=zcat.stdin, outstream=groff.stdin)  # creates helper task.
```
Expecting a filestream makes it usable in variety of cases.
Any objections, thoughts?

**Comment by dabeaz** [comment]
Would the `pipe()` call in the above example spawn the helper task and return immediately?   I'm thinking yes.   If so, who is responsible for killing it?   Maybe this is bringing it full-circle back to the issue on linked tasks.   Hmmm. Interesting.

**Comment by dabeaz** [comment]
Actually, I'm not sure it has to return right away.  I suppose `pipe()` could just block until data on the input stream was exhausted and successfully written to the output stream.

**Comment by njsmith** [comment]
So uh... I feel like I should point out that the way actual shells do this doesn't require creating two pipe objects and copying from one to the other. Instead they just make one pipe object and let the two processes talk to each other directly without the parent having to do anything at all.

```python
groff = Popen(groffcmd, stdin=PIPE, stdout=PIPE)
zcat = Popen(zcatcmd, stdout=groff.stdin)
```

**Comment by dabeaz** [comment]
Perhaps Popen is not the best example of this.   I've always viewed this feature as merely connecting two I/O streams together--not necessarily corresponding to a subprocess.  Maybe it's too much of a weird special case though.  I'm not sure.

**Comment by njsmith** [comment]
One- and two-way proxy helpers certainly are a thing that's sometimes useful. I feel like they're probably a bit out-of-scope for the curio core though? Esp. since curio core doesn't even have a "stream" abstraction (e.g. pipes and sockets have different apis for read/write).

**Comment by dabeaz** [comment]
But there is a stream abstraction.  You can call `sock.as_stream()` to create a stream from a socket.   The resulting object (`SocketStream`) uses the same API as the "file" objects used for pipes.   There is also the asynchronous "file" object in the `curio.file` which has a similar API.   In theory, it should be possible to interchange and/or connect any combination of these things.

**Comment by dabeaz** [comment]
Should note:  I need to verify the status of documentation on this.  This is one of my many "vacation" projects.   Reviewing documentation that is ;-).

**Comment by njsmith** [comment]
Oh, right. I don't want a file-like abstraction so I forgot about it :-). (The minimal stream abstraction I'm using currently has methods: `writable`, `sendall`, `recv`, `send_eof`, `close`.)

**Comment by imrn** [comment]
Pipe.go() should launch the helper and should
return immediatelly. We won't know the tempo
of data creation of the source. If there is something
we dont like we can cancel it. Running on streams make
it usable on variety of situations. Lets think it independent
of Popen. I'm currently using it similar to below example.

```python
class Pipe:
    def __init__(instream, outstream):
        self.in = instream
        self.out = outstream
        self.task = None

    async def go():
        self.task = spawn(dumpstream(self.in, self.out))

pipe= Pipe(instream=zcat.stdout, outstream=groff.stdin)
await pipe.go()

while True:
    rd = await groff.stdout.read()  # Final output we are after. 
    if not rd:
        break

pipe.task.cancel() # Normally not needed, as task will exit when instream is exhausted..
```
