### ISSUE TITLE
[DISCUSSION] Run monitor in a thread executor

### ISSUE THREAD

**Issue by ZhukovAlexander** [dabeaz/curio#137]
Recently I got obsessed by the idea to pull monitoring into the kernel space. What I mean is to me it looks like the monitor thread is a bit of an external interaction with a kernel, which somewhat violates the main principle of curio to restrict any external interaction with a kernel. 

So I'm wondering if this makes sense to launch the monitoring server as a task in a thread pool executor. With this we will reuse the curio task management system to supervise the monitor just as any other task. Or am I just trying to overcomplicate what already works fine?

**Comment by dabeaz** [comment]
I made the monitor a completely separate entity primarily to facilitate debugging.   For example, if the kernel gets locked up or some task runs away forever, the monitor can still operate and (potentially) show some useful information about what is happening.   There's definitely a bit of encapsulation being violated.  But hopefully it's for a good cause ;-)

**Comment by ZhukovAlexander** [comment]
> if the kernel gets locked up or some task runs away forever, the monitor can still operate and (potentially) show some useful

I think running it in a thread pool executor forever until the kernel shuts down should have the same effect, shouldn't it?

Other than that, I cat't imagine how to properly terminate the monitor if it's being run in a thread executor, so probably this is not so good idea :)

**Comment by dabeaz** [comment]
Closing for now.  All improvements to the monitor welcome though.
