### ISSUE TITLE
Exception handling for WantRead and WantWrite

### ISSUE THREAD

**Issue by andyxning** [dabeaz/curio#15]
I read the source code about  `Stream` class in `io` module. However, the exception handling in `Stream._read` method is confusing me. In actually it only process read functionality. So, i think it can do not need to catch `WantWrite` exception.

If i am wrong, please tell me.:)

**Comment by dabeaz** [comment]
Both WantRead and WantWrite exceptions are necessary to properly support SSL.  See https://docs.python.org/3.5/library/ssl.html#notes-on-non-blocking-sockets
