### ISSUE TITLE
Kernel shutdown errors when a worker thread is open

### ISSUE THREAD

**Issue by SunDwarf** [dabeaz/curio#150]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/workers.py", line 186, in run_worker
    future.set_result(result)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/workers.py", line 132, in set_result
    self._callback(self)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 551, in <lambda>
    future.add_done_callback(lambda fut, task=current: _wake(task, fut))
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 196, in _wake
    self._notify_sock.send(b'\x00')
AttributeError: 'NoneType' object has no attribute 'send'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/workers.py", line 188, in run_worker
    future.set_exception(e)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/workers.py", line 136, in set_exception
    self._callback(self)
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 551, in <lambda>
    future.add_done_callback(lambda fut, task=current: _wake(task, fut))
  File "/media/storage/eyes/virtualenv/curio_dev/lib/python3.5/site-packages/curio/kernel.py", line 196, in _wake
    self._notify_sock.send(b'\x00')
AttributeError: 'NoneType' object has no attribute 'send'
```

Example:

```
import queue
import threading
import curio
import time

q = queue.Queue()

def _some_thread():
    time.sleep(5)

t = threading.Thread(target=_some_thread)
t.start()
task = None

async def _worker():
    try:
        await curio.abide(q.get)
    except curio.CancelledError:
        q.put(1)  # this is crutial!

async def _main():
    global task
    task = await curio.spawn(_worker(), daemon=True)
    await task.join()

kernel = curio.Kernel()
try:
    kernel.run(_main())
except KeyboardInterrupt:
    kernel.run(curio.spawn(task.cancel()), shutdown=True)
```
Note:
  - The error *only* happens with another thread running in the background.
  - The error *only* happens when I catch the CancelledError and put an item on the queue.

This suggests that putting an item on the queue again when cancelled causes the worker thread to wake up, but because the kernel is shutting down the notify socket is dead.

The other thread being there keeps the interpreter alive, meaning the thread can still wake up to spew the error.

**Comment by njsmith** [comment]
Would it be easy to provide a [self-contained reproducible example](http://sscce.org/)?

**Comment by SunDwarf** [comment]
Sure, give me a minute or two.

**Comment by SunDwarf** [comment]
I'm sorry, I can't figure out a way to reliably reproduce the error outside of my complex library code now.

**Comment by dabeaz** [comment]
Thanks for the example.  Looking into it.

**Comment by dabeaz** [comment]
Some comments on the example.... one danger of mixing threads and curio cancellation is that threads can't actually be cancelled (there is no mechanism for doing it).   Thus, if some operation is launched in a thread (e.g., using `abide()`) and a cancellation is issued, the underlying operation will still run to an eventual completion.   The result will end up getting lost to the sands of time.   I don't really know any workaround to this due to inherent limitations in the threading library.  

That said, pretty sure the bug here is due to a callback remaining attached to the `Future` that's still attached to the thread. It's being triggered at a point in time where Curio has already torn down its notification socket.   Should be fixable with the understanding that the result from the thread is still going to be lost.

**Comment by dabeaz** [comment]
One other comment on the example, the `kernel.run(shutdown=True)` method already cancels all daemonic tasks.    So, I'm not sure you need to do anything more complicated such as spawning `task.cancel()` or anything to get it to cancel.

**Comment by dabeaz** [comment]
Fixed.

**Comment by SunDwarf** [comment]
I had actually wrote the code that I saw the error in initially before learning about kernel shutdowns and because I've used `asyncio` exclusively for the last 6 months I'm used to the explicit cancellation of all remaining tasks pattern.
