### ISSUE TITLE
Overlapped Cancellation/Timeout

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#152]
So, here's a tiny little thing I've been tumbling around in my tiny brain... what happens in Curio if a timeout happens to overlap the handling of a cancellation?   For example:

    async def coro():
       ...
       try:
             await blocking()
       except CancelledError:
             await some_cleanup()      # <- Timeout delivered here

I'm thinking that perhaps it would make sense for `task.cancel()` to also cancel any pending timeout (under the theory that if a task is already being cancelled, the delivery of any previously set timeout is immaterial--I mean, it's being cancelled!).    Beyond that, who knows?

**Comment by imrn** [comment]
What if you need to use some timeouts while handling the cancellation?
Then there is a need for classifiying timeouts in two catagories:

1) Those started before the cancellation
2) Those started after the cancellation.

Group 1 should not be delivered, where as Group 2 should be delivered.

Beyond that as we discuss cancellations It seems there is nothing exceptional
about them. Once you catch them you'll continue as if nothing new happened.

**Comment by imrn** [comment]
Lets forget about the name "Cancellation" for a second. We are talking about
a generic exception delivery mechanism to the running task.
But Cancellation has a special meaning for a task. (Cancelled status, etc..)
Should it be that way? If not what will be it relation to the timeouts.. ??
Why, what, how.. etc, etc...?

**Comment by dabeaz** [comment]
I'm less concerned about this issue at the moment although I have modified Curio so that an explicit cancellation request (e.g., `task.cancel()`) also cancels any pending timeout.   If a task is being cancelled, it's going to be bailing out of what it's doing anyways (as it's not legal to simply ignore a cancellation outright).  So, I think it makes sense to do this.

Using a new timeout in the `CancelledError` handling block is fine.  That's something different.

**Comment by imrn** [comment]
On 1/7/17, David Beazley <notifications@github.com> wrote:
> (as it's not legal to simply ignore a cancellation outright).

How can you enforce it?

**Comment by njsmith** [comment]
Same way we enforce that people write bug-free code: you can't, but if you don't do it then you suffer the consequences.

**Comment by imrn** [comment]
On 1/7/17, Nathaniel J. Smith <notifications@github.com> wrote:
> Same way we enforce that people write bug-free code: you can't, but if you
> don't do it then you suffer the consequences.

You got it this time..

**Comment by dabeaz** [comment]
It's the same way that people suffer the consequences every time they write:
 
    try:
       ...
    except:
       ...

So, by all means, go ahead and ignore cancellation ;-).

**Comment by imrn** [comment]
On 1/7/17, David Beazley <notifications@github.com> wrote:
> It's the same way that people suffer the consequences every time they
> write:
>
>     try:
>        ...
>     except:
>        ...

So is this why it is 'illegal'!? ;))

> So, by all means, go ahead and ignore cancellation ;-)

try blocks are not nice. But if they are going to exist, lets go
and have some fun... That's why I'm playing with the idea
of a general exception delivery mechanism.
Admittedly without some concrete proposal..

**Comment by imrn** [comment]
And there is some conceptual mismatch:
Curio assumes cancellations are not ignorable.
But in reality they are somehow ignorable.

Since this is not something avoidable, its better to incorporate
this reality into Curio.

**Comment by dabeaz** [comment]
I'm not going to do anything about it in Curio other than document the fact that if you ignore cancellation, then you're going to deserve every manner of programming hell that's going to be coming in your direction.   If people want to code up a bunch of unreliable/undebuggable stuff, that's their problem.  I'm only a messenger. 

"Well, it was in the documentation."

**Comment by dabeaz** [comment]
Closing this.  Less concerned about the issue than I was.  I did modify Curio so that any explicit cancellation (e.g., task.cancel()) also cancels any pending timeout.   This resolves most of my concerns--I think.

**Comment by vinipsmaker** [comment]
> I have modified Curio so that an explicit cancellation request (e.g., `task.cancel()`) also cancels any pending timeout.

Unless wrapped in `disable_cancellation()` the underlying operation that caused `t` to block should be cancelled. That's what happens in:

```python
result = await timeout_after(5, coro, args)
```

So this design is fine (and further propagating the cancellation request from `timeout_after` to `coro`, but this time that's an implementation detail from `timeout_after` and not really a “core” building block for the whole system).

On this whole matter of cancellation, maybe I can offer clarification on how things should work. `t.cancel()` should be read as “send a cancellation request for _near delivery_ to `t`”. This request cancels any underlying operation that `t` was blocked on.

For instance, imagine:

```python
await sock.read(buf)
```

`buf` must stay accessible while the operation is in progress. Being a GC'ed language, Python makes it easy for this pattern to work irrespective of the underlying choice of cancellation mechanism. But the problem doesn't disappear entirely. If buffer is reused from a pool, signalling that the task ended will signal to the rest of the application that the buffer can be reused for another operation. And that's the reason why `t` must only be awaken when the underlying operation (be it a socket or be it a timeout) that caused `t` to block in first place had a chance to react on the cancellation request. When you have the reply for the cancellation request of the underlying operation, then you can awaken `t` (if that sounds confuse to implement, take a look at io_uring to have a better illustration of the topic in hand). And it's completely valid for the cancellation reply of the underlying operation to be “operation already finished”. In this case, the correct behaviour is to deliver the result _as-is_ and defer the delivery of the cancellation request until a new suspension/interruption point is reached.

> I'm not going to do anything about it in Curio other than document the fact that if you ignore cancellation, then you're going to deserve every manner of programming hell that's going to be coming in your direction.

Why not raise `TaskCancelled` again on the next suspension/interruption point? The only way to fully ignore cancellation requests should be `disable_cancellation()`.
