### ISSUE TITLE
Should run_in_thread() allow timeouts/cancellation?

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#153]
So, there is the `curio.run_in_thread()` function that allows an arbitrary callable to execute in a thread.   There's only one problem--once running, there is no way to cancel a thread.  Thus, the supplied callable runs to completion no matter what.

This presents numerous logistical problems in the face of cancellation.  For example, if we walk away from work submitted to a thread, it still ends up completing, but the result is lost forever.   For example, suppose you tried to read from a thread queue::

    import queue
    q = queue.Queue()    # Thread queue. Not a Curio queue

    try:
        item = await timeout_after(5, run_in_thread(q.get))
    except TaskTimeout:
        print('Yawn!')

If you run this code, the `q.get()` operation runs fully to completion regardless of the timeout.  That means that eventually it will get a queue item.  However, the timeout make Curio walk away from the result.  Thus the item pulled off the queue will simply disappear.   I could imagine something like that being pretty hellish to debug,

Anyways, this is just some random thinking... maybe the `run_in_thread()` function should disable cancellation entirely.   Doing so would make a lot of things much easier to reason about.   Not having timeouts/cancellation might be a concern, but you're interacting with threads after all.   It's a foreign world.  If you really want cancellation, you should stick with coroutines.

Curious about everyone's thoughts on it...

**Comment by imrn** [comment]
On 1/9/17, David Beazley <notifications@github.com> wrote:
>     import queue
>     q = queue.Queue()    # Thread queue. Not a Curio queue
>
>     try:
>         item = await timeout_after(5, run_in_thread(q.get))
>     except TaskTimeout:
>         print('Yawn!')

As long as this exception/cancellation/timeout etc fires it is ok..

**Comment by dabeaz** [comment]
Would you care if the timeout got delayed indefinitely?   What happens if the thread operation took a minute?

**Comment by imrn** [comment]
On 1/9/17, David Beazley <notifications@github.com> wrote:
> Would you care if the timeout got delayed indefinitely?   What happens if
> the thread operation took a minute?

I'd expect the thread in which timeout is in operate normally.
That is, timeout should be on time. If the result is not ready
I'll walk away. There should be no difference for the timeout
or any other thing there. That's the reason I would be offloading
the the operation (sync or async) to the other thread.
Why would I do that if it still disturbs me?
(I'm ignoring the slowdown effects off the general CPU/core load.)

It would be my fault if the abondoned thread later screws other
things up. If the result is a thing I can not walk away why would
I put it in a timeout? If it is that important then I should sit and
wait for the result without any timeout. I should also protect
the context from any cancellation.
