### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by guyingbo** [dabeaz/curio#154]
I got exception from my project:
https://github.com/guyingbo/socks5/blob/b8b05c05b6a9207cdff8694f70be6bdb2083c57d/shadowproxy.py

```
Curio: Task Crash: ServerBase._relay
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/curio/kernel.py", line 537, in run
    traps[trap[0]](*trap)
  File "/usr/local/lib/python3.6/site-packages/curio/kernel.py", line 317, in _trap_io
    selector_register(fileobj, event, current)
  File "/usr/local/lib/python3.6/selectors.py", line 405, in register
    key = super().register(fileobj, events, data)
  File "/usr/local/lib/python3.6/selectors.py", line 241, in register
    .format(fileobj, key.fd))
KeyError: '17 (FD 17) is already registered'
Traceback (most recent call last):
  File "shadowproxy.py", line 733, in main
    kernel.run(multi_server(*args.server))
  File "/usr/local/lib/python3.6/site-packages/curio/kernel.py", line 589, in run
    selector_unregister(current._last_io[1])
  File "/usr/local/lib/python3.6/selectors.py", line 419, in unregister
    key = super().unregister(fileobj)
  File "/usr/local/lib/python3.6/selectors.py", line 250, in unregister
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '18 is not registered'
```

**Comment by dabeaz** [comment]
Hard to say for certain, but the initial error message is the kind of thing you would get if you tried to have multiple tasks wait on the same file descriptor.       The line numbers (for Curio) don't match the current version of code that's in Github so I'd try using using that to see if the problem goes away.  There have been a variety of changes/improvements made to file descriptor handling over the last few months.

**Comment by guyingbo** [comment]
I have tried version 0.4 and latest version on github, the error occur on both versions. The error does not occur frequently and I can't catch the exception in the coroutine, so it is a bit diffcult to debug.

**Comment by dabeaz** [comment]
Interesting.   I think I'd need more information.  What is happening when the bug occurs?  Is it easily reproducible or somewhat random?    Anything else to note about it?

**Comment by dabeaz** [comment]
A traceback from the current Github version would also be quite useful.

**Comment by guyingbo** [comment]
I find I installed the latest version but it was still the old version to be used before. Until now the latest version works fine, I will keep watching.

**Comment by dabeaz** [comment]
I say keep an eye on it.  I suspect that this crash could be caused by https://github.com/dabeaz/curio/issues/104.  However, if it comes up again, definitely return here.

**Comment by guyingbo** [comment]
After watching for four days,  the error never occurs with the github latest version. I belive it has been fixed.
