### ISSUE TITLE
100% CPU when sleeping on OSX

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#156]
Need to modify the kernel to either launch the kernel task or provide an alternate sleep when there are no file descriptors being watched.  Otherwise sleep results in busy waiting.

**Comment by njsmith** [comment]
For the record: this appears to be a bug in `KqueueSelector`: when it calls `kqueue.control`, it sets `maxevents` (the maximum number of events to be returned, determines an internal buffer size) to match the number of fds registered with the selector. If there are no fds, it passes 0. The value 0 is special-cased by the `kevent` syscall, causing it to return immediately. (I can't imagine why anyone thought this was useful, but it is documented: ["When `nevents` is zero, `kevent()` will return immediately even if there is a `timeout` specified..."](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2).) The real fix would be for `KqueueSelector` to add a line like `if max_ev == 0: max_ev = 1`. In the mean time of course curio has to work around it...

Also for the record, `SelectSelector` on Windows has a similar bug, which is discussed in #75.

**Comment by njsmith** [comment]
Filed upstream as https://bugs.python.org/issue29255, FWIW.

**Comment by dabeaz** [comment]
I've modified Curio to always launch its loopback task.

**Comment by njsmith** [comment]
Without having tested anything, I suspect that will fix the kqueue issue
but not the windows issue, since the loopback task doesn't actually start
waiting on its fd until after the first "pump-priming" send call, at which
point we've already give through the selector once and (on Windows) crashed.

**Comment by dabeaz** [comment]
Moved the loopback so that it initializes first.  Will probably fix that.
