### ISSUE TITLE
How should re-entrant and/or multiple kernels be handled?

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#161]
More of a general question really.  Should Curio allow multiple kernels to run in the same process?  For example, two kernels running in different threads?   What happens if some code executes the ``run()`` method inside a function when the kernel is already running?

**Comment by njsmith** [comment]
Running multiple kernels in different threads seems uncomplicated (for curio) and potentially useful - what's the argument against?

Calling `run` from inside a curio function also seems semantically straightforward and fairly easy to support (there is the one bit of code in the task-local storage stuff that gets more complicated, but it's like 3 lines total). I can't see think of any situation though where this wouldn't be a mistake, so it would make sense to me to raise an error just to help users out.

**Comment by dabeaz** [comment]
I was mainly thinking about things such as queues, locks, and other task communication mechanisms.  It would be an error for tasks from two different kernels to interact with the same queue for instance (it would most likely deadlock or behave very strangely).

**Comment by njsmith** [comment]
Oh, for sure. I was assuming the model where those are only safe to use from within the "owning" curio thread (just like now), and for communication between two curio threads it's just like any other kind of communication between curio and an external thread -- it's just an internal detail that the "other" thread happens to have its own kernel, it has nothing to do with this kernel, and one has to use some kind of curio<->thread communication mechanism.

I guess making `UniversalQueue` work in this case would be an interesting challenge though :-)

**Comment by imrn** [comment]
On 1/22/17, David Beazley <notifications@github.com> wrote:
> I was mainly thinking about things such as queues, locks, and other task
> communication mechanisms.  It would be an error for tasks from two different
> kernels to interact with the same queue for instance (it would most likely
> deadlock or behave very strangely).

Definetely. I dont think it as a logical use case..

Lets define:
Curio_Thread: A curio kernel running an async func in a thread.
Thread: Ordinary thread running a sync func.

Some cases I can think of is as follows:

1) A Curio_Thread may run a 'Sync' function in a Thread via
run_in_process/thread. This may be an ordinary Thread
or even another Curio_Thread. Then the parent is the supervisor.
No problems.

2) Run an "Async" func in Current Curio_Thread.
This is await func() or await spawn(func()).
No problems.

3) Run an "Async" func in an other Curio_Thread.
This is equiavelent to a Curio_Thread running an other
Curio_thread. See (1). No problems.

Are there any other possible combinations?

I also consider calling run() in a Curio_Thread is an error.
Just as the fact that we should avoid making a blocking
call in a Curio_Thread.

Then the question may be this:
Should we have
Curio_Thread <-> Curio_Thread and
Curio_Thread <-> Thread communication/syncronization
mechanisms? Are they really necessary?
How can we do it?

**Comment by dabeaz** [comment]
Actually, I can't think of any reason why a UniversalQueue wouldn't work across Curio kernels running in different threads.  The underlying queue is a thread-queue.   If it works for thread->Curio queuing it would definitely also work for Curio->Curio queuing across threads.   I'm going to try this...

**Comment by dabeaz** [comment]
I've tweaked UniversalQueue to work across kernels running in different threads (it can be done using a bit of thread-local storage).    I've also modified Curio to not allow multiple kernels to run on a single thread at once.

For whatever it's worth, I got to thinking about the problem of running multiple kernels in multiple threads.  I tried this experiment involving sockets and it worked fine::

    from curio import *
    from curio.socket import *

    async def tcp_server(label, sock, handle_client):
        print('Server', label, 'starting')
        while True:
            client, addr = await sock.accept()
            print(label, 'Connection from:', addr)
            await spawn(handle_client(client, addr))

    async def echo_client(client, addr):
        async with client:
            while True:
                data = await client.recv(10000)
                if not data:
                    break
                await client.sendall(b'Got:' + data)
        print('Connection closed')

    import threading

    def main(addr, nkernels):
        sock = socket(AF_INET, SOCK_STREAM)
        sock.bind(addr)
        sock.listen(1)

        for n in range(nkernels):
            threading.Thread(target=run, args=(tcp_server(n, sock, echo_client),)).start()

    if __name__ == '__main__':
        main(('', 25000), 4)

I've used a similar pattern with threads and processes in the past.  So, I suppose it shouldn't be a huge surprise that it would work okay.  Still neat.

**Comment by imrn** [comment]
Is sock.accept() thread safe?

**Comment by dabeaz** [comment]
So far as I know, yes.   Is there a specific concern?

**Comment by imrn** [comment]
4 threads will be waiting on the accept() func of the same listener socket.

That may be a concern if it is not thread safe from Curio down to the
sys calls. There are some discussions for C around the net, mentioning
that above pattern is safe and can be used for multithreaded apps.
But it is C and I can't find a clear consensus. And there is other libs,
python,... and Curio..

Anyway for just to be 100% sure I would listen and accept incoming
connection with a "Dedicated thread" and then pass it to workers for handling.
But that requires more logistics.

If sock.accept() is thread safe for sure your example is fine..

**Comment by dabeaz** [comment]
I'm not aware of it not being thread safe.   The pattern is certainly known in the Python world.  I've used it in production code.

**Comment by imrn** [comment]
This may (or still may not) "implicitly" mean it is Thread Safe at C level:

http://man7.org/linux/man-pages/man2/accept.2.html

"There may not always be a connection waiting after a SIGIO is
delivered or select(2), poll(2), or epoll(7) return a readability
event because the connection might have been removed by an
asynchronous network error or another "THREAD" before accept() is
called.  If this happens, then the call will block waiting for the
next connection to arrive."

**Comment by dabeaz** [comment]
Sure.  Not really seeing a problem here though. Curio will go back to waiting.

**Comment by njsmith** [comment]
Yeah, that code's perfectly standard and well defined. And if it weren't
for that pesky GIL it would make a lot of sense :-)

**Comment by dabeaz** [comment]
Nah, it might even mean more sense for async if tasks had non-async blocking operations taking place.  ;-).

**Comment by imrn** [comment]
Yeah, I too wish GIL, listen(1), asyncs, luck,.. (all things that may be protecting
against multithread mess up) are absent too.. ;)

Ideally for this case we need to make sure that socket doesn't
have "any" unguarded state againts threads and accept() doesn't
use it unprotected. (Replace socket with anything if you want to be
more generic.) And this should be verified for all levels of call
chain (from Curio to syscall) AND for all platforms..

Author of your favorite "concurrency library" would be last
one from whom you want hear the sentence "Well, it works.". ;)

It may actually be really the case, but you know.... :/

**Comment by dabeaz** [comment]
Closing.  Running multiple kernels in different threads should be okay.  Only safe communication is via queues though.
