### ISSUE TITLE
Why doesn't "spawn" return right away?

### ISSUE THREAD

**Issue by imrn** [dabeaz/curio#164]
Documentation says: "Spawn does not return to the caller until the
new task has been scheduled and executed for at least one cycle."

It means spawn is holding the caller on the line and this is some kind
of a sync behaviour. (At least for the initial steps.) I think caller task
should not be bothered with the initial steps of the spawned tasks.
Is this a technical necessity or any other thing?

Suppose a parent task is spawning/off-loading to many child tasks.
In this case parent's throughput is reduced by such sync behaviour.

**Comment by dabeaz** [comment]
I'm not actually sure that Curio does this right now (in fact, it doesn't).   However, the original thinking on it was probably related to the fact that you can't do anything other than send `None` to a coroutine until it's run to at least the first yield statement.  So, it might have been a guard against that.

**Comment by imrn** [comment]
Let me make it more clear:
I don't have any problem with ordinary scheduling behaviour.

But a saying "await spawn(something()) will not continue before
making some steps in something()" is an other thing.

This always puts the caller in disadvantaged state, diverging
from fair (non-clever) execution policy.

**Comment by dabeaz** [comment]
Just to clarify, the current behavior of Curio is for `spawn()` to immediately return to the caller.  The docs are out of date in this respect.

**Comment by dabeaz** [comment]
Fixed the docs to be up-to-date with current behavior.
