### ISSUE TITLE
OSError: [Errno 92] Protocol not available running on Ubuntu Bash on Windows 10

### ISSUE THREAD

**Issue by Tigercardell** [dabeaz/curio#168]
I've been running the curio examples on the windows 10 Ubuntu bash. I'm running it in the insider preview which means i'm on Ubuntu 16.04, allowing me to use python 3.5.

Ubuntu bash reports that sys.platform == 'linux' and it seems to be behaving more like linux than like windows.
Some of the examples run flawlessly e.g prodcons.py.
When  I run hello.py sort of works but as it starts it logs the following exception

Parent PID 127
Can I play?
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/c/Users/Gina/devel/curio/curio/monitor.py", line 154, in server
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEPORT, 1)
OSError: [Errno 92] Protocol not available

Wha!?!
Can I play?

**Comment by njsmith** [comment]
SO_REUSEPORT is only supported on pretty recent Linux kernels, and that's
the error you get if it's not supported; apparently Windows is not recent
enough :-). It can happen on Linux too, though.

I'm not sure why the monitor is even setting that though -- seems weird.

**Comment by Tigercardell** [comment]
It is interesting for me, these concurrent tasks.
I feel it is helping me to lay my foundations in code, as well as the scale of my understanding; In a sense, my curio...sity.

**Comment by imrn** [comment]
Mostly I use SO_REUSEPORT too (on linux). Because sometimes
subsequent uses of the same port gives an error like "Port already in use"
even there are no process hangs or similar. Using this option helps to
eliminate the error.

**Comment by dabeaz** [comment]
I'm not even sure why that SO_REUSEPORT option is in there in the first place.

**Comment by Tigercardell** [comment]
it is in a try: except: that catches AttributeError -- but in this case we get OSError instead.

Expect it is there to avoid the problem @imrn mentions -- re-using the same port eg when you are working on code that runs a monitor.    One useful side-effect is that if you fire a second one up using the same port it seems to wait until any previous process that is using that port exits.

So it seems Windows System for Linux, unsurprisingly has some quirks.

This only affects the monitor task in the hello example.

.. so the other good news is run_in_process works here.

**Comment by dabeaz** [comment]
You don't need SO_REUSEPORT to avoid the problem mentioned.  The SO_REUSEADDR option already does that.    Pretty sure SO_REUSEPORT is something that gets used if you want multiple processes to be simultaneously running and you want them all listening on the same port at the same time--achieving an effect similar to what happens when you first bind to a port and then call `fork()` a bunch of times to create a pre-forked server.

**Comment by njsmith** [comment]
Yeah, exactly. And this means that SO_REUSEPORT also has security
implications, because it allows for a limited form of "port hijacking".

Note that IIRC SO_REUSEPORT on *BSD and MacOS means something different
though.

If you *do* want to use SO_REUSEPORT you need both the AttributeError check
and the OSError check -- socket.SO_REUSEPORT is defined iff Python was
*built* on a system that had SO_REUSEPORT support, and the setsockopt call
succeeds if *running* on a system that has SO_REUSEPORT support.

**Comment by jkbbwr** [comment]
Slight hijack of thread but would it be possible to have `with_reuseport` on `tcp_socket`, makes for really handy sideways scaling.

**Comment by dabeaz** [comment]
Yeah, maybe (assuming you mean ``tcp_server()``).   Are there any other options that one would be likely to use in the pre-binding stage of a socket besides this one?

**Comment by njsmith** [comment]
Two that jump to mind are IPV6_V6ONLY and SO_EXCLUSIVEADDRUSE (a weird
Windows thing, probably should be the default there, though unfortunately
it's not entirely clear because it simultaneously fixes a security issue
*and* breaks TIME_WAIT sockets, because Windows)

**Comment by jkbbwr** [comment]
`IPV6_V6ONLY` What about non ipv6 networks?

**Comment by njsmith** [comment]
IPV6_V6ONLY is a flag you can set on ipv6 sockets (family=AF_INET6) to
control whether the same socket can also sorta-transparently speak ipv4.
You may or may not want this, depending on your v4/v6 implementation
strategy. (For example, a server could have a single ipv4+ipv6 listening
socket, but then if it logs IP addresses that people are connecting from it
needs to be prepared to handle "ipv4 mapped addresses"; for some
applications maybe it's simpler to instead have two listening sockets, one
for v4 and one for v6.)
