### ISSUE TITLE
Tagging curio releases

### ISSUE THREAD

**Issue by nchammas** [dabeaz/curio#17]
I noticed that, though curio has a [0.1 release on PyPI](https://pypi.python.org/pypi/curio), there are no [tagged releases on GitHub](https://github.com/dabeaz/curio/releases).

Do you plan to tag releases here? Among other things, it makes it easier to browse the code at a given release.

**Comment by dabeaz** [comment]
Didn't occur to me to tag 0.1 release.   Will do so in the future.

**Comment by nchammas** [comment]
Sounds good to me. You can probably retroactively tag 0.1 here on GitHub, but it probably doesn't matter much either way. Feel free to close this issue.
