### ISSUE TITLE
Async state preserving reentrant Kernel

### ISSUE THREAD

**Issue by imrn** [dabeaz/curio#172]
Currently, Kernel.run() blocks the thread until it's done with the
tasks at the hand. If curio is embedded in an other application
you should either:
- Feed the kernel with coroutines with short running times. That, is you can not have long lived and state preserving embedded async apps. 
- Or run curio in a seperate thread. But this time you need to take care of thread handling and most importantly guard against thread state dependent cross thread accesses and route them through thread safe interfaces/queues.

Here we'll discuss about providing semantics for:
- Returning from Kernel.run() on demand, preserving all async state: Coroutines and other threads should be able to trigger this action. The trigger is provisionally named as a pause() function. But suggestions for other possible mechanisms are also welcome.
- Providing re-entrant Kernel.run() so that subsequent calls will make curio continue from its previous freezed/paused state.

You can also find previous discussion at #111.

**Comment by dabeaz** [comment]
Right now, the behavior of curio is for the `Kernel.run()` method to execute until all non-daemonic tasks finish executing.  When `run()` returns, the daemonic tasks continue to persist. So, on a subsequent call to `run()`, they will still be there.   Thus, one approach that's possible now is to write code like this::

    from curio import *
    from curio.socket import *

    async def echo_server(address):
        sock = socket(AF_INET, SOCK_STREAM)
        sock.setsockopt(SOL_SOCKET, SO_REUSEADDR, True)
        sock.bind(address)
        sock.listen(5)
        while True:
            client, addr = await sock.accept()
            await spawn(echo_client(client, addr), daemon=True)

    async def echo_client(sock, address):
        print('Connection from', address)
        async with sock:
            while True:
                data = await sock.recv(100000)
                if not data:
                    break
                await sock.sendall(b'Got:'+data)

    async def start():
        await spawn(echo_server(('', 25000)), daemon=True)

    async def pump():
        pass

    if __name__ == '__main__':
        kernel = Kernel()
        with kernel:
            kernel.run(start())
            while True:
                kernel.run(pump())

In this code, the `run()` method is just repeatedly given a coroutine that does nothing.  It could do more than that, but at a minimum it causes the kernel to run a complete scheduling cycle. 

There are all sorts of various weird things about this.  For example, it's critical that every created task be marked as daemonic.  Certain things like sleeping probably don't work right (would likely sleep in the kernel for the full duration of the requested sleep time).   Nevertheless, it still sort of works.

So, one possible approach on pause/restarting would be to refine this a bit.   For example, perhaps the `run()` method is modified so that it returns as soon as its passed coroutine terminates (regardless of any other tasks that might be running).   Maybe `run()` called with no arguments causes Curio to go through a single scheduling cycle.  Perhaps I get rid of daemonic tasks altogether under this scheme (might be worth it).  

The big idea though is that if you wanted the kernel to pause, you'd basically set up your tasks first in some kind of starting coroutine.  After that, you'd repeatedly call `Kernel.run()` to drive things (either supplying a short-running coroutine or None). 

Some benefits:  The semantics of `run()` don't really have to change--it still runs the supplied coroutine and returns its value.  I don't need to add a new trap for pausing.  

Cons: Maybe it's weird having to repeatedly submit a short-running coroutine like that. It might not provide the level of control needed if you needed to pause at a specific point (although you could certainly coordinate it with various synchronization primitives).

**Comment by imrn** [comment]
Did you noticed that, this can scale linearly from just "1 cycle" to "full run"
depending on the developer's ingenuity on setting up his application structure?

Coro submitted to run is infact the "pause condition watchdog" which can
be a no-op as above or a timer or anything watching the app provided
that related sync primitives are laid before hand. Perfect..

And just to make sure, lets confirm:
For a no-op coro case, "1 complete scheduling cycle" means Kernel.run() will
just deal with ready tasks and exit. That is, it will NOT block. Right?

It's fine run() with no args stepping once. Supplying a dummy coro does not look
good. May be run() can supply it as a default. Eliminating daemons is also fine.
It seems all good to a me. Thanks for defining it fairly crafty. :)

**Comment by dabeaz** [comment]
For the "no-op" case, Kernel.run() would poll for I/O events, check for sleeping tasks, and run a single scheduling cycle of anything that happened to wake up as a result.   I would envision it as NOT blocking under any circumstance (a slight tweak would need to be made to I/O polling so that it uses a 0-timeout value).

I'm experimenting with an implementation of this at the moment.  Not ready to check in yet though.

**Comment by dabeaz** [comment]
I have committed a highly experimental implementation of this.  Here is an example on which to test:

    from curio import *
    from curio.socket import *

    async def echo_client(sock, address):
        print('Connection from', address)
        async with sock:
            while True:
                data = await sock.recv(100000)
                if not data:
                    break
                await sock.sendall(b'Got:'+data)

    async def sleeper():
        while True:
            await sleep(1)
            print('sleeping', n)

    async def start():
        await spawn(tcp_server('', 25000, echo_client), daemon=True)
        await spawn(sleeper(), daemon=True)

    n = 0
    def main():
        global n
        kernel = Kernel()
        with kernel:
            kernel.run_coro(start())
            while True:
                kernel.run_coro()
                n += 1

    if __name__ == '__main__':
        main()

If you run this code, you should see a rapidly increasing counter value being printed every second.  It should also allow incoming network connections.   The counter value should continue to increase rapidly even when connections are made.   The main() function is driving the kernel by repeatedly calling `run_coro()`.

A few critical notes:  

- This is currently implemented as a `Kernel.run_coro()` method.  That's purely for experimentation at this point.   It's expected that this would ultimately take the place of the existing `run()` method. I should note that all of the unit tests pass if I alias `run()` to `run_coro()`.   

- `Kernel.run_coro()` has the same behavior as before--running until all non-daemonic tasks finish executing.  If you want tasks to persist, but control to return, make them daemonic.

- Any tasks spawned by a daemonic task are also daemonic.

- Calling `run_coro()` with no arguments executes one scheduling cycle.   If you give an argument to `run_coro(coro)`, then it runs whatever coroutine you give it until all non-daemonic tasks finish.

Consider this a starting point.  Would be interested to have people play around with it.

**Comment by imrn** [comment]
I've replaced run() by pasting above run_coro loop nearly as is. Running
inhouse http1.x/2.0 framework with many of the curio goodies:
Handlers having many timeouts, spawns, locks, events, queues, processes
(with hefty ones), etc, etc.. So far without any glitch. Impressed.. :)

BUT with some %100 cpu core utilization, which is expected for an unblocking call.
May be an option for blocking/unblocking call is needed. Lets think about it...

**Comment by imrn** [comment]
> May be an option for blocking/unblocking call is needed. Lets think about it...

May be not. It is developer's responsibility to provide relevant coro for blocking.
What do you think?

**Comment by imrn** [comment]
Or there may be an option for one shot blocking call.

run(blocking=oneshot) may work like this:
if there are ready tasks run them an exit.
if not block until the first one, process it and exit.

Any other suggestions for possible operation modes/params?

**Comment by dabeaz** [comment]
Would need to think about the oneshot option.  One potential problem with I/O is that Curio could just sit there forever waiting for something to happen.  That's probably not what you want if you're interfacing Curio with something else. 

I could imagine a timeout option that got applied to the I/O selector perhaps.  That might be more sane.

**Comment by dabeaz** [comment]
I've added an experimental timeout option to the run_coro() method. For example:

    kernel.run_coro(timeout=0.1)

That specifies the maximum duration of I/O polling in the absence of any other work to do.

**Comment by imrn** [comment]
> Would need to think about the oneshot option. One potential problem with
> I/O is that Curio could just sit there forever waiting for something to happen.
> That's probably not what you want if you're interfacing Curio with something else.

Well, once we step outside the ideal world of curio, we are faced with the very classical
problem of "To block, or not-to block, how to block, when to block...". Infact curio is
the final result of collective iterations of finding a solution to this. Look at those huge
pile of code trying to find the right mix. Yes, the place curio is standing is the result
of too much sweat and blood. And that nobody's fault.

Anyway, that said, there are too many ways for dealing the blocking problem.
But I think we should not. We can always say "Go and get your fancy main
coordinator coroutine". And at the last resort thread are always there.

Saying this probably easy, because the developer who leaves child coros behind is
either knows what he is doing or doesn't know what he is doing. In either case he
deserves the same answer. ;)

I think we should focus on providing options for
- Cases can NOT be covered coordinator coro. "Oneshot" seems to be one of them. Or is it?
- Timers can easily be covered. May be providing a shortcut is handy. But I'm not sure.
- What else?

Lets put all those really necessary cases and decide for the final parameters for run().

We probably dont want to contribute to the electricity bill of people running curio
main run loop having certain "if conditions" evaluating false for 99.99999% of the time. ;)

**Comment by dabeaz** [comment]
I modified the `run_coro()` method so that `run_coro(timeout=None)` causes Curio to block as it normally would waiting for I/O or a timeout.   This is basically the "oneshot" behavior.

**Comment by imrn** [comment]
Still runs at %100 cpu.

Infact, it starts with <1%. But after some activity it shots to %100
and never comes back.

Commented code is the original. Runs at around <1%.

```python
def run(self, servers):
    # run(self.runservers(servers))
    kernel = Kernel()
    with kernel:
        kernel.run_coro(self.run_co(servers))
        while True:
            kernel.run_coro(timeout=None)
```

**Comment by dabeaz** [comment]
Hmmm. I'm just not seeing that behavior on my end.  What operating system is this on?

**Comment by imrn** [comment]
64-bit Arch Linux. I can debug using Pycharm. Where/What should I look for?

**Comment by imrn** [comment]
Added the helper function I use. See above..

**Comment by dabeaz** [comment]
Not seeing 100% CPU on Linux either.  So, not what to advise.  Probably need more info.

**Comment by imrn** [comment]
Ok preparing a lean setup so that current bells and whistes will not interfere.
I'll report back.

**Comment by imrn** [comment]
Your above example runs fine. Redirecting my browser to 127.0.0.1:25000
gets the echo. No jump to 100%. Good.

Probably I should find the thing in the framework which spins the loop fast.
Interestingly there is no anomally for normal run().
Any possible guesses? I'm on python 3.6.

**Comment by imrn** [comment]
Got something. While loop is innocent. In fact it never runs!

kernel.run_coro(self.run_co(servers)) never return.

That's where 100% cpu occurs.

```Python
class Tcpd:

    @staticmethod
    async def runservers(servers):
        for s in servers:
            await spawn(tcp_server(s.ip, s.port, s.handle))

    async def run_co(self, servers):
        await spawn(self.runservers(servers))

    def run(self, servers):
        # run(self.runservers(servers))
        kernel = Kernel()
        with kernel:
            kernel.run_coro(self.run_co(servers))  # <- Never returns.. 100% is here
            while True:
                kernel.run_coro(timeout=None)
```

**Comment by imrn** [comment]
What's more interesting is that all servers are operational.
Applications run without any problem.

**Comment by dabeaz** [comment]
Oh, one thing I noticed---in order for run_coro() to return, all of the background tasks have to be daemonic.   So, make sure you use `spawn(self.runservers(servers), daemon=True)`.     As for why it would be sitting there with 100% CPU, that is an interesting mystery.  I can't imagine what it would be doing there.

As a note:  I think there was a bug on OS-X that caused 100% CPU load under certain conditions (maybe if nothing was waiting for I/O).   Pretty sure that got fixed.  Maybe it's something similar here though.

**Comment by imrn** [comment]
All good now and at 0.1% load. May be that's why we should get rid of daemons.. ;)

Other finding is this:
run_co -> spawns child tcp_servers

Only making run_co daemonic solves it all.
Making other childs daemonic or not has no effect. See above..
Does this mean anything?

**Comment by dabeaz** [comment]
Daemon status is inherited when running under run_coro().   So all of those children should be daemonic even though it wasn't specified explicitly.

**Comment by imrn** [comment]
I only copied-pasted the loop, didn't noticed daemon thing. So the result is the
last 10 messages. Sorry for that.

Well, I guess the concept for the new run() is in place. As I'm testing, the full
framework up is running. It has most of the curio goodies. May be we can
go forward polishing it for the release without daemons.

What do you think?

**Comment by imrn** [comment]
Perhaps we can go over the run() interface. I'll suggest a similar convention
similar to select. That is:

1- Non-blocking: run(coro, timeout=0) -> select(..., 0). Only process ready tasks. Exit.
2- Blocking (OneShot): run(coro, timeout=None) -> select(..., None). Like 1. If none ready block until next. Process it. Exit.
3- Blocking (Hard): current run()
4- Blocking (Timeout): run(coro, timeout=5) -> select(..., 5)

An interesting result of this listing is that I think we are heading to
a "Future kind of return value" from run(). May be the task itself.

That is; run() is a way of injecting Tasks into the curio environment.
The caller of the run() will take actions according to the readiness of
the futures/tasks.

Now lets think about this interface. After having a reasonable
consensus I think, we can begin to provide details for
1,2,3,4,any_other?. Because I think they are currently in a rough form.

**Comment by imrn** [comment]
One other thing is that, if we're going through such a new
paradigm of running tasks and returning values then it will
be substantially different than current run().

Obviously we will not want to disturb current run() users. And we don't
want to be slowed by current structure and compatibility issues.

As this is going to be curio's new gateway to the sync world, probably
it is best to have current run() and the new thing as seperate interfaces.

David; you've already forked the run(). I'm also dropping "run()" on
the subject line. This thing will probably stay as experimental and
evolving for a while. Interesting days ahead. ;)

**Comment by dabeaz** [comment]
I don't see the current changes as anything other than very minor improvements to the current `run()` method.   `run()` already preserved the state of any existing daemon tasks.  I've merely tweaked it so that calling it with no coroutine makes it go through a single scheduling cycle.  The optional timeout argument allows you to specify/override the maximum waiting time on the internal `select()` call.   The experimental `run_coro()` currently passes all unit tests for the normal `run()` method.

The only additional change I'm thinking about is the `run(coro, timeout=seconds)` option.  That's an interesting option.  My inclination on that is to make it equivalent to `run(timeout_after(seconds, coro))`.

**Comment by imrn** [comment]
Let me give an example for curio tasks/futures.
They are seem to be effectively the await/spawn for the sync world.

```python
async def someasync():
   await sleep(5)
   return 1

task1 = kernel.run(someasync(), timeout=0)  # Non-blocking
task2 = kernel.run(someasync(), timeout=0)  # Non-blocking
kernel.run() # Blocking
res1 = task1.result
res2 = task2.result
```

**Comment by imrn** [comment]
Returning tasks from run() may disturb current structure.
If it can be handled same way I don't mind for single code base.

**Comment by dabeaz** [comment]
I really don't want to go in the direction of futures for the run() method.

**Comment by imrn** [comment]
Well, I actually mean we can already envision tasks as futures.
No new future thing. Just return tasks from run() and update the result when done.
That's it. Did you see example above? I'm also adding some more. No new thing.

**Comment by dabeaz** [comment]
My inclination is for Curio to stay focused on execution of coroutines .  The `run(coro)` method currently does just that.   There are many different ways by which a result could be computed and returned.  For example, the above scenario is already supported in part now:

     kernel = Kernel()
     task1 = kernel.run_coro(spawn(someasync(), daemon=True)
     task2 = kernel.run_coro(spawn(someasync(), daemon=True)
     
     # Run until task 1 terminates
     result1 = kernel.run_coro(task1.join())

     # Poll until task 2 terminates
     while not task2.terminated:
           kernel.run_coro(timeout=None)
           print('Other stuff...')

     result2 = kernel.run_coro(task2.join())

**Comment by imrn** [comment]
> My inclination is for Curio to stay focused on execution of coroutines.

Technically correct. However, such bold decleration keeps sync and async
code as seperate islands. Below approach will make more easy and
natural to mix them, while you are still staying on your focus.

> The run(coro) method currently does just that.

Yeah, same thing and complex looking. Another humane version below. ;)
It requires nothing more than below additions to Kernel and Task. (Except other
things for returning tasks from run() as I proposed in previous message.)

I'm not trying to hide asyncs. Infact I want them with sync
code everywhere. ;) Just having a curio kernel makes this possible.

```python
# Look, No asyncs!

v = kernel.await(someasync())  # Blocks until ready
print(v)

f1 = kernel.spawn(someasync()) # Will not block
f2 = kernel.spawn(someasync())
f3 = kernel.spawn(someasync())
f4 = kernel.spawn(someasync())

flist = [f1, f2, f3, f4]
shuffle(flist)     # Will work everyway.

# Async iterator without any asyncs..
for f in flist:
    print(f.val())     # May or may not block for each. See below.


class Kernel:
    def spawn(self, coro):  # Rename as getfuture if you like
        task = self.run(co, timeout=0)  # Non-Blocking
        task.kernel = self
        return task

    def await(self, coro):  # Yeah, I know await is a keyword..
        task = self.run(coro)  # Blocks until ready
        return task.result


class Task:
    def val(self):
        while not self.terminated:
            self.kernel.run(timeout=None)  # Oneshot
        return self.result

        # Above while may not even fire because some other
        # kernel iteration may already run this task to
        # completion.
```

**Comment by dabeaz** [comment]
The thing is, I *want* the worlds of async and sync to be separate islands in Curio.  Backing that statement up for a moment....

... the earliest versions of Curio had a small collection of methods on the `Kernel` class including a `spawn()` method.  However, in thinking about that, I became concerned about muddying the waters between operations performed on the Kernel by synchronous code and operations performed by asynchronous code.  For example, is it legal to use `Kernel.spawn()` in both contexts?  Can outside threads call `Kernel.spawn()`?   I also looked at the `asyncio`Event loop and it's large zoo of functions like `run_forever()`, `run_until_complete()`, `call_soon()`, `create_task()`, and whatnot.     I consciously decided to take a different direction and make the invocation of Curio as dead simple as possible.  `run()`--that is the one and only public API function for invoking Curio from synchronous code.  

Even in the proposed code above, it gets muddy real fast.  For example, consider that `Task.val()` method.  Who can call that?  Synchronous code outside of Curio? A separate thread outside of Curio?  An asynchronous task running within Curio?   Synchronous code called by an async task currently running in Curio?  Is calling the `kernel.run()` method legal in all of these contexts?  (most likely not). 

At this point, I'm not sure I want to back out of that and start adding methods to the `Kernel` class.  If someone wants to make the kernel launch a collection of background tasks, or have it return task objects, or fool around with Futures, I feel that it can all be done in the initial coroutine given to `run()`.  Although I'm fine with `run()` having a few tweaks related to scheduling/polling for the purpose of it sitting in an outside event loop, I'd like to keep everything else involving the kernel sitting on the async side of the fence.

**Comment by njsmith** [comment]
The problem with treating run as a new select, is the same problem that
select has in the first place: it's not composable. Barring threads, your
program loop can only make one blocking call, whether that's select or
curio.run_with_timeout. So somehow everything blocking has to go into that
one call. In this case it means that all blocking code has to go into
curio, leaving only non-blocking code outside curio... but you can just as
easily put non-blocking code into curio too, so what's the point of
splitting it up?

The example above with spawning tasks etc could just as easily be written
as a single async function passed to main. There's no additional power from
writing it this way; it just makes a new redundant way of writing the same
things we can already write.

The exception is that having a run_one_iteration style interface is useful
to allow really janky event loop integration where you busy-pool two event
loops in alternation, maybe with a small sleep. (And using a timeout
argument on one of the loops to implement the sleep can improve latency a
bit, but again, only for some events.) I'm not saying we shouldn't support
this. But we should recognize how limited the value is.

**Comment by imrn** [comment]
Ok. Points are:
1) Some revisions for run() for reentancy: With coros, blocking/non-blocking timeouts. Select is no model, just its timeout values: 0, 5, None. Status: On track.
2) Request for an other sibling of run() returning task. Discussed above. I'll digest it further. Closed.

So first things first. Lets polish (1) and get it to main stream.

**Comment by dabeaz** [comment]
I agree that it's kind of janky with respect to integrating with other stuff in this way (polling).  One might be able to do something more interesting by making a custom Selector object and using that with the Kernel.   However, that's not something I've spent much time exploring.

**Comment by dabeaz** [comment]
Regarding a reentrant `run()` method... that's not likely to happen.   Too many horrible things that can go wrong with that.

**Comment by imrn** [comment]
Oops.. What about the proof concept you provided and we've tested? Will it be shelved?

**Comment by dabeaz** [comment]
I'll probably keep the `run_coro()` method,  but have it replace the existing `run()` method.  It already passes all of the existing unit tests.  It adds a few tweaks to current behavior that are unlikely to affect any existing Curio code.    Also, it's significantly faster than `run()` if someone decides to use it for polling or submitting a lot tasks to the kernel from sync code. 

I'm still undecided about the fate of daemonic tasks.  For now they're staying.

**Comment by dabeaz** [comment]
Also, the new `run()` method is, itself, implemented as a coroutine.  So, it adds a whole extra level of meta-coroutine insanity to the whole thing which is already quite insane.  Maybe that's good. Or not ;-).

**Comment by imrn** [comment]
So understand that run() will grab some goodies from this discussion but will not be reentrant? Correct? What about timeouts for blocking, non-blocking thing?

**Comment by dabeaz** [comment]
It will have the current features of the `run_coro()` method which include the various timeout options.   By re-entrant, I am referring to the problem of allowing `run()` to be invoked when `run()` is already running (e.g., recursive calls, etc.).  That won't be allowed.   Repeated calls to `run()` one after the other are fine.

**Comment by imrn** [comment]
Oh No!!. Nobody requested calling run() recursively... Reentrancy for Kernel.run() was always "Calling run() one after an other" in the sense that Reentrant lock() acquired multiple times... I'm surprised that we got this far if everyone understood it that differently... :))

Anyway I'm now happy with run_coro(). If you can organize timeouts similar to sockets/select I'll be happier. 

1) Non-blocking: run(coro, timeout=0) -> select(..., 0). Only process ready tasks. Exit.
2) Blocking (OneShot): run(coro, timeout=None) -> select(..., None). Like 1. If none ready block until next. Process it. Exit.
3) Blocking (Hard): current run()
4) Blocking (Timeout): run(coro, timeout=5) -> select(..., 5)

Let's get it in the main stream.. Thanks for the effort.

Probably I'll be still after run() returning tasks.
But first let this reentracy ;) stabilized and I myself digest your comments.
Thanks again.

**Comment by dabeaz** [comment]
I'm keeping it, but there are probably only going to be three cases:

1.  run(coro) .  Runs a coroutine until it and all non-daemonic tasks it might have spawned terminate.
2. run(timeout=val).   Run daemonic tasks through a single cycle of the scheduler.  timeout value gets passed to select().  timeout=None makes it block.
3. run(coro, timeout=secs). If a timeout is given in combination with a coroutine, I'm going to make it apply the effect of `timeout_after(secs, coro)` on it.   

I'm still on the fence about the daemonic/non-daemonic task distinction.  For now, I'm keeping them.

**Comment by dabeaz** [comment]
Just a note. `run_coro()` is now gone--it was always just temporary for experimentation.  The normal `run()` method has this behavior.

**Comment by imrn** [comment]
Ok. Let's confirm, document and propose detailed behaviour of this thing.
This post also has the hidden agenda of removing daemons. Please provide
feedback citing item #. After contributions, I'll compile a new set and post again.

1) Kernel is a pool of tasks.
2) Kernel.run() and spawn() add tasks to this pool.
3) Kernel.run(coro=None, timeout=None) has the following properties:
4) timeout determines maximum time for polling ready events.

5) if coro==None: run() always returns None, and (6, 7, 8) applies.
6) timeout==None: Run ready tasks. Wait for and process next event. Return. (OneShot)
7) timeout==0: Only run ready tasks. Return. (Non-blocking)
8) timeout>0: Process ready and upcoming events within x secs. (Timeout-Blocking)

9) if coro!=None: (10, 11, 12) applies:
10) timeout==None: Run until the task is done. Return result. (Hard-Blocking)
Like traditional run(), PLUS other tasks may still remain in the pool, ready to be run on next iterations.
11) timeout==0: Add the task to the pool, only run ready tasks like (7). Return None.
12) timeout>0: (8) + Return task result if it is ready in x secs.
Otherwise raise TimeoutError to the caller of run(). On timeout, the task will still remain in the pool and will continue execution on the following iterations. (Recall threads?) If user really wants task to exit/be_killed after x secs, he himself should handle it in the coro.

Proposal: Stepped OneShot driving until all done:
```python
while kernel.tasks:
   kernel.run()
```

**Comment by dabeaz** [comment]
I'm not willing to have that much complexity built in to the `run()` method.   Run currently operates as follows:

1. run(coro).  Runs the specified coroutine to completion and returns its result.
2. run(). Runs the kernel for a single scheduling cycle, executing work from background tasks (if any), and returns.

That's basically it.  If an optional timeout is given, it imposes a deadline either by causing a TaskTimeout exception to be delivered to the supplied coroutine or by supplying the timeout argument to the `select()` call used for I/O polling.

I don't really want to have it do anything more than this.

**Comment by imrn** [comment]
The list is not a request list. Infact, it is a procedural documentation for run() as I understand. So far I 'think' it is an extended versions of yours. May be some items are not covered. That's why I wrote it to confirm and possibly talk about daemons removal. I 'think' this could be basis for it.

**Comment by dabeaz** [comment]
There are things in the list that appear to attach different semantics to different values of the timeout when, in fact, the timeout is just passed directly to `select()` and there's no other interpretation of it.  `run(coro, timeout=secs)` is the same as `run(timeout_after(secs, coro))`.

**Comment by dabeaz** [comment]
Of course, maybe my head is just fried from yesterday (always a distinct possibility).   The main thing is that `run()` only has those two operations.

**Comment by imrn** [comment]
No problem. May be it should have a better presentation on what is currently covered and 
what can be possible discussion points? I think daemon removal thing is related with
whole picture. I'll post a more digestible version. Meanwhile, can you post item wise questions
if there are any?

**Comment by imrn** [comment]
Yes.. The main theme is always like that: With a coroutine and without. No deviation.

**Comment by njsmith** [comment]
That seems like two pretty different meanings for timeout= overloaded onto
the same argument?

**Comment by dabeaz** [comment]
How do you figure?  If given no coroutine, the timeout is the maximum amount of time that will be spent waiting for something to happen.  If given a coroutine, the timeout is the maximum amount of time it's allowed to run before being cancelled.    Seems fairly consistent to me unless I'm missing something.

**Comment by imrn** [comment]
Second Version:
Normal text defines existing behaviour. Bold text highlights areas subject to discussion.

This text is an overview for Kernel.run() describing modes of operation.
It is expected to provide a basis for documentation as well as a general
picture for possible removal of daemon tasks.

Kernel is a pool of tasks. `run(coro=None, timeout=None)` and `spawn(coro)`
add tasks to this pool.

`coro` is the main parameter for the `run()` function. `timeout` is behaviour modifier
determining max time for polling ready tasks.

Presence or absence a `coro` leads to two major modes of operation.
Regardless of the mode, each call to `run()` processes all ready tasks until
it returns. Additionally it runs as follows:

1) `run(timeout=None) -> return None`
a) `timeout==None`: Run ready tasks and return. If there is None, wait until
the next. Process it. Return. (OneShot-Blocking)
b) `timeout==0`: Just run ready tasks if there are any. Return. (Non-blocking)
c) `timeout>0`: Like (a). But wait at most x secs. (Timeout-Blocking)

2) `run(coro, timeout=None, cancel_on_timeout=True) -> return result` / **None**
a) `timeout==None`: Run until task is done. Return result. (Hard-Blocking).
This is traditional run() **PLUS other tasks may still remain in the task pool, to be processed on next runs.**
b) `timeout==0`: **Add the task to the pool and process ready tasks. Return None.**
c) `timeout>0`: Like (a). But wait at most x secs.
**TimeoutError raised to the caller of run() if the result is not ready.** Task will be canceled **OR it will remain in the task pool depending on `cancel_on_timeout` param.**

Examples:
TODO: Provide examples for above.

Proposal: Stepped OneShot driving until all done:
```python
while kernel.tasks:
   kernel.run()
```

**Comment by dabeaz** [comment]
The `run(coro)` option above describes non-existant behavior.   `run(coro)` always runs the supplied coroutine and non-daemonic tasks to completion. It returns the result of the coroutine.   There are no options to detach from it or have it operate in the background.   If this is wanted, then use `run(spawn(coro, daemon=True))` instead.

I don't anticipate any of those options (a) - (c) being supported.

**Comment by dabeaz** [comment]
This is not so much a comment on the specifics of `run()`, but more of a general thought about repeatedly invoking Curio to make it do things...

In the big picture, the primary use case of Curio is in problems related to I/O handling--especially network handling.  Potentially, this could involve a substantial number of I/O operations under load.  Because of that, I'm not sure it would make sense to drive Curio by repeatedly invoking `run()`.   For example, if you invoked `run()` on a periodic timer (say 10ms), you would introduce a 10ms latency into nearly single I/O operation.  The only way to get around that would seem to be repeated calls to `run()` as fast as possible---except that it leads to busy waiting and a 100% sustained CPU usage.  Neither option seems particularly desirable to me.

For something like a GUI, the I/O problems are largely alleviated if you put Curio in charge and you make periodic callouts to the GUI on a time interval.   Alternatively, if you put Curio and the GUI in separate threads and hook them up via queues, the I/O performance is also solved. 

I'm not sure this makes much sense or not.  I guess I'd be more interested in knowing more about the use case for structuring things in a way where the Curio `run()` method is repeatedly triggered like this.  Are there are a lot of I/O operations being performed in the background?  If not, what is Curio being used for in this environment?

**Comment by imrn** [comment]
- Embedding curio into sync applications which would not mind some blocking (short or long). That is; blocking indefinitely or for sometime waiting Curio return back. The sync app will block anyway if it does the same work itself. You may even adjusting the blocking time depending on the application creating a "time shared thread". Note that fine control of blocking time time is crucial for adaptation. "Long or short Blocking" is the keyword. Without it, continous call method will lead to %100 cpu- a useless method.

- And there is run wise slicing. Depends on if your workload can be divided to small calls or not. Parent application sends small work loads it see fits. Or a big one with oneshot/timeout
combinations. Infact blocking time and runwise slicing are two sides of the coin.

These are the reasons for requesting fine controlled run().

**Comment by imrn** [comment]
libevent/libuv both have similar functinality:

https://pyuv.readthedocs.io/en/v1.x/loop.html
http://www.wangafu.net/~nickm/libevent-book/Ref3_eventloop.html
