### ISSUE TITLE
different processing according to content length in channel module

### ISSUE THREAD

**Issue by andyxning** [dabeaz/curio#18]
I have read the `channel` module, something is confused me. the method `send_bytes` process write differently according to the length of `buf`. 
```
async def send_bytes(self, buf):
        '''
        Send a buffer of bytes as a single message
        '''
        size = len(buf)
        header = struct.pack('!I', size)
        if size >= 16384:
            while header:
                try:
                    nsent = os.write(self.fileno, header)
                    header = header[nsent:]
                except BlockingIOError:
                    await _write_wait(self.fileno)

        else:
            buf = header + bytes(buf)

        m = memoryview(buf)
        while m:
            try:
                nsent = os.write(self.fileno, m)
                m = m[nsent:]
            except BlockingIOError:
                await _write_wait(self.fileno)
```
I don't know why we need do this.

**Comment by dabeaz** [comment]
First a note:  the channel module is an active work in progress and subject to change or removal at any time.

Regarding the implementation, the special casing is there to address performance issues related to the TCP Nagle Algorithm.

**Comment by andyxning** [comment]
i know Nagle Algorithm, however can you explain why the length of the content to be written is related to the special processing and why we choose the magic and opaque number `16384`. :)

**Comment by dabeaz** [comment]
The whole point of the code is to avoid writing a pair of small messages (in that case, the data is combined into a single message).   The number 16384 is somewhat arbitrary.   Not too big. Not too small.

**Comment by dabeaz** [comment]
Just a note that I am probably going to remove the channel.py file from curio.  It was just something I was messing around with.   Think I'm going to keep curio highly focused on low level I/O.  If I implement channels, it will be part of a different package that depends on curio.

**Comment by andyxning** [comment]
Ok, i got it. And i still think it is a good lib. :)
