### ISSUE TITLE
AutoDocs, CI and Badges

### ISSUE THREAD

**Issue by brifordwylie** [dabeaz/curio#19]
Super kewl project :)  Might be nice to have those cute Autodoc/CI/test/coverage badge thingies. The setup is pretty boilerplate and I've done it for other projects https://github.com/kbandla/dpkt (for instance). One of the nice things is the services can 'chime in' on PRs (see https://github.com/kbandla/dpkt/pull/188) as an example... Makes taking contributions a bit easier/nicer.. 
So @dabeaz will have to register this github project with the following services [readthedocs, travis, coveralls, landscape] or some other set based on his preferences for these things. Once that's done I (or someone else) can setup the boilerplate hooks.

**Comment by brifordwylie** [comment]
Just read @dabeaz tweet "So, am I allowed to not care about badges on github?"    so.. umm.. I'll just close this... :)

**Comment by dabeaz** [comment]
I apologize for the snarky comment on Twitter.   

For the moment, I'd like to keep this issue open because I'm still thinking about it.   In the big picture, I'm not such a huge fan of "gamification" of software development.   So, having a lot of project badges for all sorts of things doesn't appeal to me that much.  On the other hand, there probably are a few things related to testing and so forth that could be incorporated here.  I'm open to specific ideas, but have been a little short on time.  So, specific patches would definitely be considered.

**Comment by dabeaz** [comment]
Should note: There is a curio test suite that can be run as 

python3 -m curio.test

That might be a starting point for some CI configuration.

**Comment by brifordwylie** [comment]
It's all good, badges ARE overrated :) but CI and automatic documentation are definitely great things to have. All of this should be viewed as a complement for this project, people like the project they want to see it grow and improve (including me). Cheers to all...

**Comment by zoidbergwill** [comment]
Maybe it's worth breaking this issue up into smaller focused issues with the specific ideas that have a +1 from @dabeaz, so it's easier to see which ones have been implemented?

**Comment by dabeaz** [comment]
Last couple of weeks have been insane so I'm a bit behind.  I turned on Travis CI for the project and will keep and eye on it.

Forgive the dumb question, but is the proposal to add "automatic documentation" asking to generate documentation from the code itself somehow?   (In addition to the documentation that's already part of the project).

**Comment by brifordwylie** [comment]
http://sphinx-doc.org/latest/ext/autodoc.html, so for example   the entire top half of this page https://dpkt.readthedocs.org/en/latest/examples.html was generated with the following line in the rst file 

    automodule:: examples.print_packets

I'm going to concur with @zoidbergwill that this issue should be split up into separate issues and that this issue should just be closed.
