### ISSUE TITLE
Py3.5 release on pypi

### ISSUE THREAD

**Issue by jkbbwr** [dabeaz/curio#194]
There have been a number of really important changes recently providing ZMQ, asyncio bridges and cleanups and speedups to UniversalQueue and others. Is there any chance we can publish a build on pypi with these changes that still includes Python 3.5

Currently tests pass on 3.5 if you ignore the `test_asyncgen` file and this can be done pragmatically inside `conftest` using the following code

```
import sys 

collect_ignore = []
if sys.version_info < (3,6):
    collect_ignore.append("test_asyncgen.py")
```

**Comment by dabeaz** [comment]
Should be possible to push another release although I'm still in the midst of doing some cleanup, improvements to debugging, etc.  I'm also teaching a course the next three days. So, it might not be until the weekend.

**Comment by jkbbwr** [comment]
I personally could live with that :) :+1:

**Comment by jkbbwr** [comment]
Can I get an update on this release going out? We want to pin against pypi not github for some work we are doing that needs asyncio bridge

**Comment by dabeaz** [comment]
Arg! Got on a big code cleanup/testing kick that snowballed into a larger project over the last few days and am in the middle of a number of things at the moment.   Definitely hoping to have something by week's end.  Sorry.   The wait will be worth it I think though...

**Comment by jkbbwr** [comment]
It sounds like it will be! Glad to know.

**Comment by dabeaz** [comment]
I've bumped the release on PyPi.   I'm still working on a lot of stuff, but recently went through a documentation round that introduced incompatibilities.  This will bring the docs in line with the version on PyPi.

**Comment by jkbbwr** [comment]
Thanks! You need a tipjar or coffee donate button or something.
