### ISSUE TITLE
Use intersphinx for cross-linking to Python docs

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#21]
http://sphinx-doc.org/latest/ext/intersphinx.html

E.g., the `selectors` module should be automatically linked to the Python docs.

**Comment by zoidbergwill** [comment]
I've started working on adding this [here](https://github.com/dabeaz/curio/compare/master...zoidbergwill:intersphinx?expand=1), I've done all mentions of the `selectors` module. 

I was considering adding links to the standard lib documentation for some marked down Python keywords, like `yield from` and `async`/`await` but I'm not sure if that's overkill.

**Comment by brettcannon** [comment]
Any progress, @zoidbergwill ? Could you possibly send a PR for what you have for the selectors module so that others can help fill in other gaps?

**Comment by zoidbergwill** [comment]
I wasn't sure what other keywords would be good to link, so I didn't add any others. I was waiting for suggestions, but should've asked more directly.

I opened a PR for the selectors stuff: https://github.com/dabeaz/curio/issues/26
