### ISSUE TITLE
'never joined' message when adding terminated tasks to task group

### ISSUE THREAD

**Issue by goldcode** [dabeaz/curio#212]
While using TaskGroup.add_task(coro) it's possible in my application that the coro which was added is sometimes already terminated. in such cases (and only such:terminated case) even after waiting for all tasks in the task group.
```
async for task in g:
    task.result
```
i get the following:
`... state='TERMINATED') never joined`

**Comment by dabeaz** [comment]
I've pushed a change that may fix this.  The main purpose of the message is to identify tasks that fall off the face the earth and are never looked at.   In this case, I've modified the ``task.result`` property to mark the task as "joined".

**Comment by goldcode** [comment]
works with 
```
async for task in g:
    task.result
```
but doesn't work for `g.join()`

**Comment by goldcode** [comment]
_identify tasks that fall off the face the earth_
i have had situations where there are tasks which i'm not particularly interested in knowing the outcome of. use case is in objects with observer pattern. in such cases, the object simply emits an event which results in a task or chain of tasks being spawned. but the object itself is not interested in the results of such tasks. i have resorted to the hack of spawning daemon tasks in such cases.

**Comment by viehwegerlib** [comment]
How can I modify the code below to deal with the Warning mentioned above?

```
import time
import warnings
warnings.filterwarnings('once')
# https://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

# WARNING:curio.task:Task(id=868, name='worker',
# <coroutine object worker at 0x1112e90a0>, state='TERMINATED') never joined

import curio
import asks
# We could use grequests or a similar solution. However, async is the future,
# so let's invest in it.
asks.init('curio')


def chunks(l, n):
    '''
    Yield successive n-sized chunks from l (stackoverflow, 312443).
    a = [1, 2, 3, 4]
    list(chunks(a, 2))
    # [[1, 2], [3, 4]]
    Returns empty list if list empty.
    For overlapping chunks, see windows()
    '''
    for i in range(0, len(l), n):
        yield l[i:i + n]


uid_list = []
for i in range(24):
    uid_list.append('AEVV030000' + '{:02d}'.format(i))

url_list = []
base = 'http://www.ebi.ac.uk/ena/data/view/'
for uid in uid_list:
    url_list.append(base + uid + '&display=fasta')


results = []


async def worker(sema, url):
    async with sema:
        r = await asks.get(url)
        print('foo')
        results.append(r)
        print('got ', url)


async def main(url_list):
    sema = curio.BoundedSemaphore(value=8) # Set sofa size.
    for chunk in chunks(url_list, 2):
        for url in chunk:
            await curio.spawn(worker(sema, url))

# TODO:
# deal with warning:
# Task(id=187, name='worker', <coroutine object worker at 0x1111f85c8>, state='TERMINATED') never joined
# join? http://curio.readthedocs.io/en/latest/tutorial.html

curio.run(main(url_list))
```

**Comment by goldcode** [comment]
One option would be to use a [TaskGroup](http://curio.readthedocs.io/en/latest/reference.html#task-groups). you are getting the warning from curio because you aren't joining on the return of your spawn task. `TaskGroup` used as a context manager automatically does the joining for you.

**Comment by viehwegerlib** [comment]
In my case, I am getting database entries, which are not related, i.e. if one query fails, the other should stay alive. Is there a way to accomplish that with a context that joins automatically?

Also, suppressing the warnings with `warnings.filterwarnings('ignore')` does not suppress them. Why could that be?

**Comment by viehwegerlib** [comment]
modified the code and it works, thanks :)

```
async def main(url_list):
    sema = curio.BoundedSemaphore(value=8) # Set sofa size.
    async with curio.TaskGroup() as g:
        for url in url_list:
            await g.spawn(worker(sema, url))
```
