### ISSUE TITLE
aredis - ERROR

### ISSUE THREAD

**Issue by wku** [dabeaz/curio#218]
*****
Attempt to connect asynchronous redis 
Causes an error
######

import curio
import aredis
import asyncio

async def run():
    print('run')
    redis = aredis.StrictRedis(host='127.0.0.1', port=6379, db=0)
    await redis.flushdb()
    await redis.set('bar', 'foo')
    bar = await redis.get('bar')
    print(bar)

if __name__ == '__main__':
    # So works
    # loop = asyncio.get_event_loop()
    # loop.run_until_complete(run())

    #does not work
    curio.run(run)

"""

.....
File "/home/wku/anaconda3/lib/python3.6/asyncio/tasks.py", line 390, in _wait
    yield from waiter
  File "/home/wku/anaconda3/lib/python3.6/site-packages/curio/kernel.py", line 844, in _run_coro
    traps[trap[0]](*trap[1:])
TypeError: '_asyncio.Future' object is not subscriptable
.....
"""

**Comment by SunDwarf** [comment]
Asyncio libraries are not compatible with curio without using the compatibility bridge.

**Comment by wku** [comment]
How to make bridge compatibility?
