### ISSUE TITLE
Avoid printing to stderr when exception is caught

### ISSUE THREAD

**Issue by ariddell** [dabeaz/curio#224]
My expectation (from Python) is that when I catch an exception, I shouldn't see anything in stderr.

Is there any way to suppress the ``RuntimeError`` being written to stderr in the following case?

```
import curio

async def bad():
    raise RuntimeError('bad task')

async def go():
    async with curio.TaskGroup() as tg:
        task = await tg.spawn(bad)
        try:
            result = await task.join()
        except curio.TaskError as e:
            print('caught the exception', e.__cause__)

curio.run(go)
```

Thanks for curio! This is much easier to use than asyncio.

**Comment by dabeaz** [comment]
All output in Curio is routed through the logging module.   So, one way to silence the output would be to configure logging to ignore it.   There is also a debug flag to run that can silence it.

    curio.run(go, debug=None)

**Comment by ariddell** [comment]
That does the trick!
