### ISSUE TITLE
tcp_server_socket() not available in curio module

### ISSUE THREAD

**Issue by Nikratio** [dabeaz/curio#240]
https://curio.readthedocs.io/en/latest/reference.html#curio.tcp_server_socket claims there is a curio.tcp_server_socket() function. However, this function only seems to exist in curio.network.

**Comment by funkybob** [comment]
https://github.com/dabeaz/curio/blob/master/curio/__init__.py#L12

However

https://github.com/dabeaz/curio/blob/master/curio/network.py#L7

So it looks like it was omitted from the __all__

**Comment by dabeaz** [comment]
Fixed.
