### ISSUE TITLE
Debugging options not documented

### ISSUE THREAD

**Issue by Nikratio** [dabeaz/curio#241]
https://curio.readthedocs.io/en/latest/reference.html#the-kernel says:

> debug is a list of optional debugging features. See the section on debugging for more detail. 

...but there is no debug section on that page, nor in the table of contents.

**Comment by dabeaz** [comment]
Curio is a volunteer project.  Pull requests that address gaps in the documentation are certainly welcome.

**Comment by dabeaz** [comment]
Wrote a section of reference docs on the debugging options.

**Comment by goldcode** [comment]
thanks for the documentation. i looked through https://curio.readthedocs.io/en/latest/reference.html#debugging-and-diagnostics which looks new to me but couldn't figure what i want to do, namely, get the list of currently running tasks and their callstacks. similar to what curio.monitor provides.

**Comment by dabeaz** [comment]
Oh, that's an interesting possibility.    Would the list of currently running tasks be obtained from within Curio (i.e., within a running Curio Task) or is the list being obtained from outside Curio (i.e., maybe from a separate thread)?

**Comment by goldcode** [comment]
in my use case it would suffice from within a curio task. i.e. if the health check task found some unhealthy symptoms, it logs all tasks and their call stacks.

**Comment by dabeaz** [comment]
Add a get_all_tasks() coroutine that returns a list of all active tasks.  Tasks have a traceback() method that will return a formatted traceback showing where the task is executing.  A where() method returns (filename, lineno) for a task.  For example:

     for task in await get_all_tasks():
             filename, lineno = await task.where()
             print(task.name, filename, lineno)
