### ISSUE TITLE
Clarify documentation of TaskGroups

### ISSUE THREAD

**Issue by Nikratio** [dabeaz/curio#244]
From the documentation, it is not clear to me:

- are task groups inherited? I.e., if a task in a group spawns more task, do the end up in the same group?
- are task groups hierarchical? I.e., if a task in a group creates another group, does it become a "subgroup"?
- It seems that when a task A creates another task B using `curio.spawn`, a cancellation of task A does not affect task B. However, if task A first creates a task group, and then spawns B in that task group, then cancellation of A implies cancellation of B. This seems not just undocumented, but also wrong.

It would be great if this could be clarified in the documentation.

**Comment by dabeaz** [comment]
Will work on docs.   FYI,  there is no relation between the top level `spawn()` function and the `TaskGroup.spawn()` method. Nor is there any kind of hierarchy or relationship between different Task Groups.  For a Task to be part of a group, it must be explicitly spawned from it or added to the group.

**Comment by dabeaz** [comment]
Added notes to better indicate the lack of relationships between task groups and the top-level spawn() function.
