### ISSUE TITLE
Unsafe generators and async context managers

### ISSUE THREAD

**Issue by Fuyukai** [dabeaz/curio#247]
Currently, using an async context manager like so will always fail:

```py
@asynccontextmanager
async def something():
    try:
        yield (await some_other_action())
    finally:
        await cleanup()
```

Trying to use the context manager would cause a RuntimeError when the generator is instantiated. The normal fix is to wrap the agen in an `async with curio.meta.finalize(...)` but that's not possible without creating a custom context manager.

**Comment by imrn** [comment]
The problem is that Python 'sync' runtime drives the "finally:"
section, so that you can not have any asyncs there.

**Comment by dabeaz** [comment]
Need more context: where is "acontextmanager" coming from?

**Comment by dabeaz** [comment]
Does it work if you do this:

    from curio.meta import safe_generator

    @acontextmanager
    @safe_generator
    async def something():
          ...

**Comment by njsmith** [comment]
Yeah, the safety test really is "is it safe to use this without a context manager", and `asynccontextmanager` is, by definition, a context manager :+)

**Comment by njsmith** [comment]
The clown nose there is a typo but I'm gonna leave it.

**Comment by SunDwarf** [comment]
Oh, okay, that makes sense. This issue probably makes more sense as just preventing the error from occurring from an acontextmanager then.

**Comment by dabeaz** [comment]
There's nothing that can't be solved with more levels of frame-hacking.  Two clown noses might be warranted.

**Comment by imrn** [comment]
On 1/24/18, David Beazley <notifications@github.com> wrote:
> There's nothing that can't be solved with more levels of frame-hacking.

Yes there are ways.
But does that mean the user can use ordinary generator forms, or
he/she should built special (split?) forms emulating
try/finally etc..

**Comment by dabeaz** [comment]
Instead of magic, perhaps Curio should just provide its own decorator for it:

    from contextlib import acontextmanager as real_acontextmanager
    def acontextmanager(func):
          return real_acontextmanager(safe_generator(func))

**Comment by dabeaz** [comment]
Fixed.  Curio now detects the use of @contextlib.asynccontextmanager.
