### ISSUE TITLE
Task Exit exception

### ISSUE THREAD

**Issue by skgbanga** [dabeaz/curio#262]
In [the curio task model](https://curio.readthedocs.io/en/latest/devel.html#the-curio-task-model) following example is given to show `TaskExit`

```py
from curio import *

async def coro1():
    print('About to die')
    raise TaskExit()

async def coro2():
    try:
        await coro1()
    except Exception as e:
        print('Something went wrong')

async def coro3():
    await coro2()

try:
    run(coro3())
except TaskExit:
    print('Task exited')
```

It is also mentioned that `TaskExit` is a subclass of BaseException, and wouldn't be caught by handlers looking for `Exception`. 

As a result, I did not expect the above to print "Something went wrong"

However, I get the following output when I run the above example:

```
About to die
Something went wrong
```

**Comment by Dobatymo** [comment]
According to https://github.com/dabeaz/curio/blob/master/curio/errors.py `TaskExit` inherits from `Exception` not `BaseException`.

**Comment by skgbanga** [comment]
Thanks @Dobatymo It seems the only exception which is derived from `BaseException` is `KernelExit`.

**Comment by kawing-chiu** [comment]
Yeah, the documentation is wrong and should be updated. Also, the doc on `TaskExit` is not adequate. The example is a poor demonstration of `TaskExit`:

- In the example, if we just return instead of raise `TaskExit`, it's perfectly fine.
- If `TaskExit` is changed to some other user-defined exception, the example works fine, too. So what is the point of `TaskExit`?

**Comment by dabeaz** [comment]
I will review what's happening with TaskExit.   I believe that the original intent was that if a task wanted to cleanly exit from a deeply nested set of calls, it could raise TaskExit much like normal code could raise SystemExit to cause Python to terminate.    It's entirely possible that TaskExit isn't fully implemented.  I will check.

**Comment by dabeaz** [comment]
Honestly, I don't know what TaskExit is used for or what I was thinking (apparently nothing).  I thought about making it mean something more concrete, but I've decided to just delete it instead.  If someone really wants something like this, they can just make their own custom exception and raise that.
