### ISSUE TITLE
performance problem --- a delay when task come to the curio.run func

### ISSUE THREAD

**Issue by JmSeason** [dabeaz/curio#270]
here is my code:
---------------------------------------------
```
from curio import *
import time
from curio.debug import traptrace, schedtrace
import logging

logging.basicConfig(level=logging.DEBUG)

async def task1():
    while True:
        await sleep(0)
    
async def task2():
    while True:
        await sleep(0)

async def run_tasks():
    async with TaskGroup(wait=any) as g:
        t1 = await g.spawn(task1)
        t2 = await g.spawn(task2)
        
async def main():
    task = await spawn(run_tasks)
    while True:
        await sleep(0)
    await task.join()
    
run(main, debug=traptrace)
```
------------------------------------------------------

when i run this, i got console output below:
---------------------------------------------------
INFO:curio.debug:TRAP:1531291958.432000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.432000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.433000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.448000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.448000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.449000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.464000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.464000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.465000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.479000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.479000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.479000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.495000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.495000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.495000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.510000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.510000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.510000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.526000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.526000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.527000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.542000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.542000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.543000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.557000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.557000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.557000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.573000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.573000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.573000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.588000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.588000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.588000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.604000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.604000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.605000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.620000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.620000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.620000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.635000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.635000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.635000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.651000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.651000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.651000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.666000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.666000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.666000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.682000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.682000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.683000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.698000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.698000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.698000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.713000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.713000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.713000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.729000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.729000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.729000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.744000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.744000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.744000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.760000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.760000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.760000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.776000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.776000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.776000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.791000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.791000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.792000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.807000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.807000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.807000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.822000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.822000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.822000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.838000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.838000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.838000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.854000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.854000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.854000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.869000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.869000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.870000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.885000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.885000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.885000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.900000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.900000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.900000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.916000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.916000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.916000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.932000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.932000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.933000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.947000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.947000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.947000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.963000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.963000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.963000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.978000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.978000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.979000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.994000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.994000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291958.994000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.010000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.010000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.010000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.025000:Task(id=2, name='main'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.025000:Task(id=4, name='task1'):Traps._trap_sleep:(0, False)
INFO:curio.debug:TRAP:1531291959.025000:Task(id=5, name='task2'):Traps._trap_sleep:(0, False)
.........
--------------------------------------------------

my question is that why task turn to the 'main' task it would delay about 0.015 seconds, but my main or task1, task2 did nothing(just sleep)

**Comment by dabeaz** [comment]
What version of Curio? What operating system?  What version of Python?

**Comment by JmSeason** [comment]
curio version :0.10
os : windows 7
python : 3.5.2

**Comment by JmSeason** [comment]
o, i had tried trio in the same environment, it won delay when task switch

**Comment by njsmith** [comment]
Well, of course I do think trio is pretty cool, but... my point is that if you try to use `time.monotonic` to measure task switch latency on Windows then you probably won't get accurate measurements. So if that's what you're doing, then even if trio seemed to "win", it might be a coincidence or artifact rather than an actual difference between trio and curio.

**Comment by JmSeason** [comment]
i see, do you think it is a bug?  because i use curio in my project on windows, because of the `time.monotonic`(you said, maybe), my project is slow, when i get the curio debug logs, it is also has the problem i said above, so i run a simple test code(above) to see if my code problem, so i found the problem in curio, but i did not try in linux, again, you think it is a bug?

**Comment by dabeaz** [comment]
Is this performance test a realistic representation of any actual code?  I don't see how a bunch of rapidly switching tasks with sleep(0) would be anything like an actual application involving I/O.

**Comment by JmSeason** [comment]
my project use curio, i have many tasks, i tried curio.sleep(0) to schedule these tasks, when i print curio debug log, i found some delay(about 0.015 second) when a task turn to other task, so i write a simple test code(above) to see if my problem

**Comment by JmSeason** [comment]
yes, i did not do I/O operation, i will try for some kind of I/O operation

**Comment by JmSeason** [comment]
i try to use trio replace curio in my project, than i won get this problem, when i use curio, my project finished in 2.5 seconds, when i use trio in my project,  my project finished in 0.24 seconds, that is very different, i don't think curio would be that slow, maybe the problem is the windows `time.monotonic`, i don't have an idea about this now

**Comment by imrn** [comment]
And did your account for os and cpu cache warm up period?
Do you get same numbers for both frameforks when you
run them 10-20 times in a row?

**Comment by imrn** [comment]
And are you planning to deploying someting real
which is facing internet on a windows machine?

**Comment by JmSeason** [comment]
yes, i take many test times, every time result is the same, and my project is running on windows with python, my program is not facing internet, it is a desktop client program

**Comment by dabeaz** [comment]
There's really not much for me to work with on this bug report because the supplied code and described application is so vague.   Curio is not large.  The main kernel loop is not doing much.   The only thing that comes to mind is perhaps some kind of Windows-specific thing related to I/O polling.  Curio uses the Python default selector for I/O polling which is based (AFAIK) on select().  Maybe there's some kind of performance issue with that.

Alternatively, perhaps Trio is making an optimization to not poll for I/O if it knows that know tasks are actually waiting for any I/O.

**Comment by JmSeason** [comment]
well, i have many tasks, i want to use sleep(0) to schedule tasks, i also take some test code below

```
import curio
import timeit

async def task():
    for i in range(1000):
        await curio.sleep(0)        

async def run_tasks():
    start = timeit.default_timer()
    async with curio.TaskGroup() as g:
        for i in range(3):
            await g.spawn(task)
    span = timeit.default_timer() - start
    print('span {} s'.format(span)) 
 
curio.run(run_tasks)
```
in curio, i got span about 15.6 seconds, there is another code below

```
import trio
import timeit

async def task():
    for i in range(1000):
        await trio.sleep(0)
        

async def run_tasks():
    start = timeit.default_timer()
    async with trio.open_nursery() as nursery:
        for i in range(3):
            nursery.start_soon(task)
    span = timeit.default_timer() - start
    print('span {} s'.format(span))

trio.run(run_tasks)
```
in trio, i got span about 0.26 seconds, there is a bit difference, is that i should not use sleep(0) to schedule tasks, if is yes, what ways should i do to schedule tasks

**Comment by dabeaz** [comment]
Did a bit of experimentation with this and on Windows, sure enough, about 15 seconds.  On my Macbook, it ran in about 0.02 seconds.   So, there is definitely some kind of platform-specific performance issue involved there.   However, I also looked closely at the Curio code and found that sleep(0) makes a task go through the entire sleep cycle anyways.   I modified it to special case 0 as a fast-reschedule and that made the problem go away.   I pushed this change yesterday. Try it and see what happens in your application.

Might worth some amount of investigation to see what's causing that massive slowdown on Windows.  There's really not much going on in the code other than calls to time_monotonic() and select().   I'll investigate further when I get a chance.

**Comment by imrn** [comment]
On 7/14/18, David Beazley <notifications@github.com> wrote:
> I modified it to special case 0 as a fast-reschedule.

"sleep(0)" is a defacto alias for async yield/reschedule/
voluntary_context_switch/whatever_you_may_call.
But I think is a bit awkward.

How about defining the concept and giving it a proper function name?

My suggestion:

await reschedule()
await sleep(t)  # is a noop for t <= 0

**Comment by dabeaz** [comment]
Curio already has `await schedule()` that does this.   It's the same as `sleep(0)`.
