### ISSUE TITLE
How do I create a pool of connection?

### ISSUE THREAD

**Issue by pttdev** [dabeaz/curio#281]
Let say I want to maintain 20 ssh connection at once (using asyncssh) and when I'm done with an connection I can "pop" it out of the pool and "append" another one. Would you guys please suggest me a solution? I take a walk into curio docs but not sure which should I use.
Thank you in advance!

p/s: for more detail, I need an api http server in role of pop and append connection to the pool.

**Comment by imrn** [comment]
Can you some more info about topology?
ie. source and destination interfaces..

I understand that writer app at the source does
not bother with destination. All it wants is writable
stream. Right? It is an interesting configuration.

**Comment by dabeaz** [comment]
I'm not sure the Curio solution to make a connection would look much different than a typical solution involving threads.    Since this isn't really an issue with Curio itself, I'm closing this issue.  It might be a suitable entry for the "How To" guide though.
