### ISSUE TITLE
Tagline proposal.

### ISSUE THREAD

**Issue by caulagi** [dabeaz/curio#286]
I was wondering if it is ok to propose a tagline for this project. If so - I want to propose

> turtles all the way down

... maybe somewhere in the readme.

PS: sorry about opening an empty issue and then editing

**Comment by dabeaz** [comment]
But what if curio is something that piled high into the air?   Also, what if it's not turtles?

**Comment by caulagi** [comment]
Sorry, I should have been clearer. What I was thinking when I submitted this issue is - all the api's provided by curio, other than `run`, seem to be async (which seemed to me to be an useful mental model). 

However, I see that there are many synchronous methods as well - `grep -r 'def ' curio | grep -v async | grep -v '__'`. I was hasty in my initial submission and should have looked around some more. Apologies.

**Comment by dabeaz** [comment]
No problem.   TBH, my comment was a bit of weird humor.... there is a history of weird taglines and strange commentary surrounding curio and its docs.   So, I was thinking in those terms.

In terms of APIs, almost all of Curio's API is still async however.  So "turtles all the way down" is not too far off the mark in that respect.
