### ISSUE TITLE
Suspend after setting event

### ISSUE THREAD

**Issue by charron** [dabeaz/curio#293]
Hello, I am just starting with curio, loving it so far but I have found some unexpected behavior with events (curio 0.9, python 3.7.3).
In the following code I have two "waiters" setting an event each in a queue and a "setter" getting them from the queue and setting them.

```python
import curio
q = curio.Queue()

async def waiter(value):
    evt = curio.Event()
    evt.value = value
    await q.put(evt)
    await evt.wait()
    print('processing', value)

async def setter():
    async for evt in q:
        print('setting', evt.value)
        await evt.set()
        await q.task_done()

async def main():
    w1 = await curio.spawn(waiter, 1)
    w2 = await curio.spawn(waiter, 2)
    s = await curio.spawn(setter)
    await w1.join()
    await w2.join()
    await s.cancel()

curio.run(main)
```
The output is 
```
setting 1
setting 2
processing 1
processing 2
```
although I would have expected
```
setting 1
processing 1
setting 2
processing 2
```
namely, that the "waiter" processing the event during the `await evt.set()` of the "setter".
If this is the expected behavior, how would I get the one I am looking for?

**Comment by imrn** [comment]
If I'm not missing something obvious, it's not an unexpected behaviour. If you need multiple setters to execute in sequence then you should syncronize them too. Note that, tasks behave similar to threads (well, not exactly but you can easily get my point.) If multiple setters is not a requirement, then I'd use a single looping setter.

**Comment by imrn** [comment]
Opps.. Wrong answer. ;) I'm deleting my comment..

**Comment by imrn** [comment]
Hopefully this is the correct one: Once setter starts running, and there is nothing to make it pause at an async point, if prerequisites for the continous execution is satisfied. Hence you get that output.

**Comment by charron** [comment]
Thanks a lot for the explanation and implementation suggestion, it works exactly as desired. It seems that `curio.schedule()` is not documented but given its one line implementation I guess I could have come up with it if I was more familiar with the concepts...
