### ISSUE TITLE
`curio.Queue.put` does not appear to work from sync context as documented.

### ISSUE THREAD

**Issue by pipermerriam** [dabeaz/curio#299]
Looking at the documentation here: https://github.com/dabeaz/curio/blob/0ac46615a2c009f327aba0632b193eb36df3695e/docs/devel.rst#synchronousasynchronous-queuing it suggests I should be able to use `curio.Queue.put` from a sync context without using await.

I'm still new to `curio` so maybe I've missed something, but I was unable to make this work (though it does work if I use a `curio.UniversalQueue`.  Wanted to confirm that I'm not missing something here.

**Comment by dabeaz** [comment]
I think this is a documentation error.  It should be using `UniversalQueue`.    I've made a fix to the documentation.
