### ISSUE TITLE
yield from wasn't used with future

### ISSUE THREAD

**Issue by billyshambrook** [dabeaz/curio#30]
Hey, great package with a nice interface.

I am trying to use curio with other packages (e.g. aioamqp) that are written using the asyncio.coroutine decorator. When I try to await from these in a coroutine being run by the curio kernel, I am getting the following error:

```
Curio: Task Crash: foo
Traceback (most recent call last):
  File "/Users/billyshambrook/venv/lib/python3.5/site-packages/curio/kernel.py", line 365, in run
    op, *args = current.coro.send(current.next_value)
  File "/Users/billyshambrook/.pyenv/versions/3.5.1/lib/python3.5/asyncio/futures.py", line 359, in __iter__
    assert self.done(), "yield from wasn't used with future"
AssertionError: yield from wasn't used with future
```

The code I am trying to run is...

```
import asyncio
import curio


@asyncio.coroutine
def bar():
    yield from asyncio.sleep(2)


async def foo():
    await bar()


kernel = curio.Kernel()
kernel.run(foo())
```

Is there anyway around this? or must all coroutines used use the new python 3.5 `async` syntax?

Thanks,

**Comment by dabeaz** [comment]
Curio is not compatible with asyncio so it's unlikely that any of those functions would run on the kernel.   Interoperability with asyncio is an open issue that would require investigation.
