### ISSUE TITLE
Re-upload source distribution without tests/__pycache__

### ISSUE THREAD

**Issue by jonringer** [dabeaz/curio#301]
if you download the source from pypi, and do `pytest test/` you will get something similar to

```
ImportError while loading conftest '/build/curio-0.9/tests/conftest.py'.
py._path.local.LocalPath.ImportMismatchError: ('conftest', '/Users/beazley/Desktop/Projects/junk/curio/tests/conftest.py', local('/build/curio-0.9/tests/conftest.py'))
```
the tests are picking up the __pycache__ directory and reading invalid information.

**Comment by dabeaz** [comment]
I have no idea what this would even be.  Is this a bug in pytest?

**Comment by jonringer** [comment]
sorry, the markup is eating some of the formatting

there's a `tests/__pycache__/` in the source package on pypi. So when you run pytest, it will default to using the the cache. Specifically in this case, there's a pyc for conftext.py and it has a resolved path from your machine.

**Comment by jonringer** [comment]
to reproduce:
```
$ curl -O https://files.pythonhosted.org/packages/e4/61/6e7daab81d17c47296c63c346d794c29e95218a7bceba88bf4a57cf7bb27/curio-0.9.tar.gz
$ tar xf curio-0.9.tar.gz
$ cd curio-0.9
$ virtualenv env
$ source env/bin/activate
$ python -m pip install -e .
$ python -m pytest . # fails

# to fix
$ rm -r tests/__pycache__/
$ python -m pytest . # succeeds
```

the folder acutally takes up quite a bit of space
```
# after downloading
$ du -hd0 curio-0.9.tar.gz
472K    curio-0.9.tar.gz

$ tar xf curio-0.9.tar.gz
$ du -hd0 curio-0.9
2.4M    curio-0.9

$ du -hd0 curio-0.9/tests/__pycache__
1.1M    curio-0.9/tests/__pycache__

# after deleting
$ rm -r curio-0.9/tests/__pycache__/
$ tar czf curio-0.9-slim.tar.gz curio-0.9/
$ du -h curio-0.9-slim.tar.gz
280K    curio-0.9-slim.tar.gz
```

**Comment by jonringer** [comment]
I actually like that you package the tests, and would like to keep them in the source distribution. I'm not super familiar with doing python packaging, but i think something like ` recursive-exclude __pycache__ *.pyc *.pyo *.orig` in the MANIFEST.in to prevent cache files from appearing in the wheels would be nice.

**Comment by dabeaz** [comment]
Ugh.   Sadly, I can't update an already existing release file on PyPi.   That said, Curio is probably overdue for a release update anyways.   I've had a number of minor cleanup items on my list for awhile so maybe I'll take care of that and do it soon.

**Comment by jonringer** [comment]
For most people this isn't an issue, it's just that nixpkgs will run tests if available by default, and it's preferred in the nix community. 

But thank you for you work in FOSS, it's appreciated :).
