### ISSUE TITLE
Q: asyncio bridge, take 2

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [dabeaz/curio#309]
@dabeaz David:

1. there was an abandoned attempt for `asyncio bridge` provider:
https://github.com/dabeaz/curio/pull/188
https://github.com/dabeaz/curio/issues/190

2. here is another solution, with cross-process, cross-framework, rpc-like approach:
* [basic_trunk.py](https://github.com/random-python/data_pipe/blob/master/src/main/data_pipe/basic_trunk.py)
* [basic_trunk_test.py](https://github.com/random-python/data_pipe/blob/master/src/test/data_pipe_test/basic_trunk_test.py)

3. do you think this kind of implementation should be made part of `curio` ?

**Comment by dabeaz** [comment]
My current thinking on Curio is that I want it to remain small.   To this end, the preferred way of making Curio communicate with other environments is via queues (i.e., UniversalQueue).   This approach currently works for both threads and for asyncio.   I don't know whether I'd add more functionality than that to curio itself.   If someone whats to do something more advanced, it should probably be a separate library.

**Comment by Andrei-Pozolotin** [comment]
makes sense, thank you.
