### ISSUE TITLE
FR: contextvars support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [dabeaz/curio#310]
1. there was a failed attempt of `contextvars` support:
* https://github.com/dabeaz/curio/pull/276
* https://github.com/dabeaz/curio/commit/26f795300c032a3a88b4c4601de6307a74b4e6f8

2. with a promise "to revisit" :-)
https://github.com/dabeaz/curio/pull/276#issuecomment-437637540

3. please revisit

**Comment by dabeaz** [comment]
Support has just been added.

**Comment by Andrei-Pozolotin** [comment]
thank you. please release

**Comment by dabeaz** [comment]
I am going to be reverting the prior patch and going in a different direction with this.  The main problem is that mutating global state as with contextvars is basically unsound. It also seems to play very poorly with threads which an issue for many Curio features.

I will have something that can work with contextvars if you are so inclined to use that approach and understand its limitations.
