### ISSUE TITLE
3.6 support dropped

### ISSUE THREAD

**Issue by stharding** [dabeaz/curio#319]
I'm using curio in a project that unfortunately has a pretty hard 3.6 target. Is 3.6 support likely to be supported by 1.x or do I need to pin the curio version to 0.9?

**Comment by dabeaz** [comment]
I just removed one Python 3.7 dependency (contextvars) from the core that might help.  There are still a handful of failing tests on Python 3.6 (just checked), but they are mostly related to asyncio and to contextvars.

**Comment by agronholm** [comment]
The 1.3 update changed the minimum Python version to 3.7, meaning it will no longer work with PyPy. Is there any chance this could be reversed?

**Comment by dabeaz** [comment]
I pushed a new version.  However, this is the last 3.6 release.   I'm not operating some kind of software support business so people can keep using old versions of Python forever.

**Comment by agronholm** [comment]
Thanks!

> I pushed a new version. However, this is the last 3.6 release. I'm not operating some kind of software support business so people can keep using old versions of Python forever.

Neither are many other F/OSS authors (such as myself). Still, I like to maintain compatibility with the latest PyPy3 version in my own projects.
