### ISSUE TITLE
Add custom marker for tests that require internet

### ISSUE THREAD

**Issue by carlwgeorge** [dabeaz/curio#320]
Hello!  I'm the maintainer of the python-curio RPM package in Fedora.  I was working on updating it to your latest version, but the test suite did not pass.  After some troubleshooting I realized that 96ed9c5375ef6c24b373870f757994268cae36a8 adds tests that make outgoing network connections.  The Fedora build system does not permit this for their package builds.  Would you consider adding a custom marker to make it easier to skip tests that require internet connectivity?  I have [implemented this in my fork](https://github.com/carlwgeorge/curio/commit/08ccecb62cfafe9c292914e7826b440eaecd30c9), modeled after a [pytest example](https://doc.pytest.org/en/latest/example/markers.html#marking-test-functions-and-selecting-them-for-a-run).  I was preparing to send a pull request before I noticed that your [contributing guidelines](https://github.com/dabeaz/curio/blob/master/CONTRIBUTING.md) state pull requests are invite only.  What do you think?

**Comment by dabeaz** [comment]
I'm ok with a PR for this.  If there is anything that can be done to fix the test, that's good too.

**Comment by carlwgeorge** [comment]
Awesome.  I've opened #321.

If I'm reading this code right, I imagine "fixing" them would require having something listen on localhost port 25000 and 443 with TLS.  I'm not sure how something like that would be implemented, but for now just making these type of tests easily skippable is good enough for me.
