### ISSUE TITLE
Curio's queue as an idependent project

### ISSUE THREAD

**Issue by kafran** [dabeaz/curio#322]
Hey David. I would like to suggest to publish the Curio's Queue as an independent project/package. The two project I know to communicate between async (curio or asyncio) and threads are the curio's queue and janus' queue, but curio's has a much cleaner interface. Every time I'm gonna use asyncio with threads I import curio's UniversalQueue.

**Comment by dabeaz** [comment]
The honest answer is that I don't have the bandwidth to support or engage with the community on something like this as an independent project at the moment.    However, it's not a lot of code.  In fact, I live-coded an asyncio version of the UniversalQueue code at PyGotham in 2017 (https://www.youtube.com/watch?v=x1ndXuw7S0s).    So, if someone were inclined to make such a project, it might not involve a huge amount of work.

**Comment by kafran** [comment]
Ok. I never did this before but I could try. =)
