### ISSUE TITLE
Grammar issue in the docs for `Task.result`

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#325]
It says "If accessed before the a terminates". I think it was meant to say, "If accessed before the task terminates".

Opened #324 prematurely before reading the contributing guide. Sorry about that.

**Comment by dabeaz** [comment]
It's not a problem. The contributing "guide" is mainly there to reflect the fact that I'm happy with the current color of my bikeshed.

**Comment by brettcannon** [comment]
Thanks to the one you gave me at PyCon US way back when, mine is still green as you told me. 😉
