### ISSUE TITLE
Pytest plugin conflicts with AnyIO's

### ISSUE THREAD

**Issue by agronholm** [dabeaz/curio#327]
Curio's pytest plugin wraps any test coroutine function that contains the keyword `curio` anywhere. This causes problems for the AnyIO pytest plugin which, when testing against Curio, does cause `curio` to appear on this list. The fix is to do:
```python3
if pyfuncitem.get_closest_marker('curio'):
```
instead of
```python3
if 'curio' in pyfuncitem.keywords:
```
in `curio/pytest_plugin.py`.

This of course would be easier to test if the async tests in curio's test suite were coroutine functions and relied on curio's own pytest plugin to run them.

**Comment by dabeaz** [comment]
If someone wants to rewrite Curio's test suite, I'd consider a pull request.

**Comment by agronholm** [comment]
> If someone wants to rewrite Curio's test suite, I'd consider a pull request.

I'll give that a shot if it means this change can go in.

**Comment by dabeaz** [comment]
It depends on what the change involves.   If it's going to load up Curio with things like type-hints, external dependencies, and extra tooling, then it will probably be rejected.    Would suggest writing and proposing a *small* example first.

**Comment by agronholm** [comment]
The only change I'm interested in is the one-line change outlined in the issue description. I thought you wanted me to write the test suite to use coroutine functions instead of running a local coroutine `main` function explicitly with the kernel fixture.

**Comment by dabeaz** [comment]
I'm okay with the one-line change.    The issue of Curio's own test-suite is a bigger one.  It's something that I might look at someday, but it's not a high priority right now.  If someone else wanted to look at it, I'm fine with that as long as it's mindful to the constraints of extra tooling/cruft above.

**Comment by agronholm** [comment]
I made the comment about the test suite only because this piece of code not seem to be covered by the test suite so proving that it works correctly would be difficult.

**Comment by dabeaz** [comment]
Maybe just a single test to test that then.  It's contributed code that I've had no involvement with so it's somewhat off my radar to be honest (sorry).

**Comment by agronholm** [comment]
I'll add that test.

**Comment by agronholm** [comment]
All done; ready for review.

**Comment by agronholm** [comment]
As AnyIO v2.0.0 final release approaches, I would appreciate a patch release that includes this fix. Otherwise developers will get confused when their async tests fail in subtle ways. I've worked around this by adding `-p no:curio` to AnyIO's own test suite, but I'm hoping to avoid having to document this as a general workaround.

**Comment by agronholm** [comment]
Thank you for the new release!
