### ISSUE TITLE
Dave task sometimes experiences starvation

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#33]
The maintainer of this project (Dave) sometimes experiences a delay in responding to issues and pull requests.  What's the story?

**Comment by dabeaz** [comment]
I am often teaching Python courses and doing other work that pays the bills.  Also, I have a family and kids which have higher priority than working on this.   Thus, work on curio will often take place in brief sprints throughout the year as time permits.   If you've submitted an issue or a pull request and I haven't responded, it's probably because I'm buried up to my eyeballs in some other project.  I will try to address each issue however so please be patient.

Cheers,
-Dave

**Comment by kdart** [comment]
No worries. :-) I know how it is.
