### ISSUE TITLE
Missing doc cross-links in API reference

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#34]
The latest test run found at https://travis-ci.org/dabeaz/curio should have no warnings about references in the documentation.

Once all warnings have been eliminated then `-W` can be added to the doc testing command to make sure all warnings are treated as errors.

**Comment by dabeaz** [comment]
I might be dense here (forgive me)... Not sure what I'm seeing what this issue is referring to.  Can you clarify?

**Comment by brettcannon** [comment]
So if you go to any of those subsections of the reference you will find some mention of something that should be hyperlinked but isn't. E.g., if you look at http://curio.readthedocs.org/en/latest/reference.html#Task.join you will noticed that `TaskError` isn't a hyperlink even thought it could be.

**Comment by brettcannon** [comment]
PR #41 covers a good amount of the TODO list. The rest either require dealing with references to exceptions before they are defined or the lack of docs for curio.network.Server (#42).

**Comment by dabeaz** [comment]
Will review some of these things.  I may have intended the Server class to be an internal implementation detail rather than something that someone would create directly.   For example, the create_server() function is the preferred function for creating a server.  Hmmm.  Looking at the code now, I might change how some of this works slightly. Good catch.

**Comment by brettcannon** [comment]
Basically I'm of the mind that if something gets mentioned, it should be documented *somehow* so that it can be cross-referenced and not leave people wondering "what the heck is this class the docs are mentioning?" Now that "somehow" can simply state "this is class should be considered opaque and simply passed around between different parts of the API", but there should be *something* so no one is questioning whether the docs simply overlooked the class or if they really don't need to know anything about it.

**Comment by brettcannon** [comment]
At this point the only thing missing in the docs is a definition for `curio.ssl.SSLContext` to link to.
