### ISSUE TITLE
Document curio.network.Server

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#42]
The reference guide doesn't seem to mention any of it beyond mentioning it.

**Comment by dabeaz** [comment]
Looking at the code.  Do you think Server is something that anyone would ever want to subclass or manipulate directly?  Would like to balance extensibility and easy of use (or at least not having to think about it much).

**Comment by brettcannon** [comment]
I doubt it is critical to subclass. The only reason I brought up documenting it is  that the docs reference it but without saying what the heck it is (and thus I couldn't write cross-references for it). Basically if people are expected to call it then they should know what methods it has, otherwise at least mention the class exists even if it is meant to be considered rather opaque.

**Comment by dabeaz** [comment]
Server is gone in the current release.  So, problem solved ;-).
