### ISSUE TITLE
Monitor port number not configurable in Kernel

### ISSUE THREAD

**Issue by ColMcp** [dabeaz/curio#48]
The Monitor class can be configured with a port number but, as far as I can see, the Kernel class or the run() convenience function cannot be so configured. 

Unfortunately the default port is already in use on my machine. It would be useful to be able to use an environment variable (CURIOMONITORPORT ?) to specify the port to be used.

**Comment by dabeaz** [comment]
Hmmm.  Yes, this should be addressed.   The short-term fix is to do this:

import curio.monitor
curio.monitor.MONITOR_PORT = 12345    

Do this before launching the kernel.   You can change the port number when connecting to the monitor using a command like 'python3 -m curio.monitor 12345'.

**Comment by ColMcp** [comment]
Thanks for the work-around.
