### ISSUE TITLE
UDP Server

### ISSUE THREAD

**Issue by russadams** [dabeaz/curio#51]
I looked for this type of library when I found Twisted doesn't have python3.5 support. I watched a video on YouTube of you at a conference (which was humorous and very informative) and began to research to develop some concurrency for my specific purposes.  In the hunt, I came across curio and after reading a little from the Docs,  and long before reaching the end of the page, I knew that it was your code and decided to try to implement it.  
   That being said,I am instituting a UDP server with clients and was surprised that socket.DATA_GRAM isn't supported with curio."socket wrapper" ; curio.network.tcp_server is being called.  I looked through the Docs and did not see any mention of UDP or DATA_GRAM.  Will udp_server be supported with curio.socket?

**Comment by dabeaz** [comment]
There is an example of UDP sockets in the curio/examples directory (udp_echo.py and udp_echo_client.py).   The Socket wrapper class definitely has the sendto() and recvfrom() methods commonly used with UDP.  That said, I think there probably should be some kind of high level function added to the curio.network module to make it easier.    I will do that.  Am open to ideas on the API.

**Comment by russadams** [comment]
I overlooked it entirely and literally. Thanks for the work you put in on all of your open source projects, videos, and books.
