### ISSUE TITLE
Inconsistency between README.rst and docs/index.rst

### ISSUE THREAD

**Issue by drkjam** [dabeaz/curio#6]
The broken link under "Can I contribute?" was fixed in index.rst (https://github.com/dabeaz/curio/blob/master/docs/index.rst#questions-and-answers), but it is not in sync with README.rst (https://github.com/dabeaz/curio#questions-and-answers) which is still broken.

**Comment by dabeaz** [comment]
Oh yeah.  Fixed (hopefully).
