### ISSUE TITLE
Run the test suite under OS X on Travis

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#60]
I have a PR ready to go in https://github.com/brettcannon/curio/tree/travis-osx but I'm waiting for #59  to be dealt with so there's no merge conflict.

**Comment by dabeaz** [comment]
You've lost me.  What does #13 have to do with this?

**Comment by brettcannon** [comment]
Absolutely nothing. 😄 Read the wrong number off of the pull request summary list. It should have been #59
