### ISSUE TITLE
Use py.test to verify code examples in docs are valid

### ISSUE THREAD

**Issue by brettcannon** [dabeaz/curio#61]
py.test apparently has a way to execute code examples found in Sphinx docs. Might be helpful in order to make sure that the docs stays up-to-date with the code.

**Comment by jab** [comment]
ref: (commented lines of) https://github.com/dabeaz/curio/blob/bf2cd7b/pytest.ini

**Comment by dabeaz** [comment]
The documentation often features partial code fragments and other things aimed at readability over testing.   Closing this for now.
