### ISSUE TITLE
Twisted and Curio

### ISSUE THREAD

**Issue by artyprog** [dabeaz/curio#78]
Hello,

Would  it  be wise to use Curio inside a twisted server ?

Regards

**Comment by BonemealPioneer** [comment]
Curio and twisted are completely different in the means of API, both libraries are meant to be standalone, it would essentially be pointless to do this.

**Comment by artyprog** [comment]
Thank you for your advise

**Comment by dabeaz** [comment]
Although it's true that curio is a completely different thing than Twisted, the idea of some kind of interoperability isn't so far-fetched.   One of the major goals of curio has been to remove the specifics of the underlying event loop from the picture (considering it to be a low-level implementation detail).   For example, you don't normally interact with the underlying Curio kernel in any way other than through coroutines using await.   In theory, it might be possible to swap in a different kernel implementation that would allow Curio applications to run on top of Twisted with few, if any, changes.  I've actually thought about trying this as a kind of API experiment, but have been a bit pressed for time lately.   So, it's not something I'm likely to look at right this moment.

My PyOhio talk has some further thinking about some of these ideas:  https://www.youtube.com/watch?v=E-1Y4kSsAFc

**Comment by artyprog** [comment]
Thank you David

Le dimanche 4 septembre 2016, David Beazley <notifications@github.com> a
écrit :
