### ISSUE TITLE
Curio Discussion Forum

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#80]
I have created a Discourse-based discussion forum with a section for Curio.  http://forum.dabeaz.com/c/curio

**Comment by jab** [comment]
Nice! Just went to sign up, but noticed it requires submitting the signup form (including an email address and password) over HTTP, so thinking of holding off until HTTPS is supported. Maybe check out [Let's Encrypt](https://letsencrypt.org/)?

**Comment by jab** [comment]
(I think the Oauth-with-GitHub option doesn't help, since that'd cause GitHub to send your server users' tokens over HTTP, and their session cookies would continue to be sent over HTTP too.)

**Comment by dabeaz** [comment]
Good catch.  I will investigate.   This is completely hosted by them so hopefully this is not hard to set up.

**Comment by dabeaz** [comment]
Ah. It seems I just need to click a button and pay a slight bit more for that.  Might take a few days, but it will get set up.

**Comment by brettcannon** [comment]
Since the forum is mentioned in the README should this issue be closed?
