### ISSUE TITLE
[QUESTION] Experiment with alternative task scheduling policies

### ISSUE THREAD

**Issue by ZhukovAlexander** [dabeaz/curio#91]
IMHO, the `curio` library actually looks more like an operating system, rather than just a ***library for performing concurrent I/O***, which I think is intentional. Therefore many aspects of the OS development also apply to it. We already have a `Kernel`, a context of execution (aka **Task-local storage**), processes (aka ***Tasks***), system calls (aka `traps.py`)etc. 

So, one thing that I notice: the scheduling policy is a FIFO policy (this is actually the case for all major asynchronous libraries and frameworks), which is the simplest one, but by far not the optimal one. 

Given that `curio.Task` already has some execution stats (`Task.cycles`, `Task.state`, `Task. _last_io `), we can use this stats to come up with more sophisticated scheduling, like *Multilevel Feedback Queue*, which should improve the performance and usability under the real world workload. There were some experiments with threads scheduling already done: http://dabeaz.blogspot.com.au/2010_02_01_archive.html, which demonstrated a performance boost in a threaded environment, which should also apply to the coroutines world as well.

So the question is: should we try to use an advanced scheduling in `curio` and what benefits if any it'd bring?

**Comment by dabeaz** [comment]
Quick answer:  Yes, we should make it possible to have alternative scheduling in Curio.

This is actually something that's been on the back of my mind.  However, in the interest of keeping the first few releases simple and manageable, it's been more of a back-burner project. 

Given the lack of true preemption, the flexibility of scheduling is probably going to be a bit more limited than in a real operating system.   However, I could definitely envision some scheme in which the kernel prioritizes tasks in some way.    It could also be interesting to explore priority scheduling in the context of soft-real time processing--it gets especially interesting if you mix it up with synchronization on locks, queues, and other things.   

If we go this route, I think my main concern would be making it modular in some way.   For example, the basic curio kernel could stick with FIFO as a default.  If you wanted alternative scheduling, it should be something that could be plugged in an optional feature.   I don't think it would be hard to do that.   Right now, the kernel uses collection.deque objects in a most minimal way.   That could certainly be expanded out into something more featureful.

**Comment by ZhukovAlexander** [comment]
> If we go this route, I think my main concern would be making it modular in some way.

Sure, pluggable queue implementation looks like a way to go. This also aligns well with the [customizable kernel clock](https://github.com/dabeaz/curio/issues/92). 

IMO, MLFQ scheduling could easely obey the same API as dequeue, so modularity should not be a concern. One of the implementation questions that bothers me is the exact mechanism for supplying custom components. I can envision two general approaches here:

-  keep pluggable components in the global namespace and patch them to allow alternative implementations
- dynamically inject them at the time of a kernel initialization

**Comment by ZhukovAlexander** [comment]
Apparently, right now the outcome of the tests results is dependant on the task scheduling policy.
To demonstrate this, I've replaced the `kqueue` with the LIFO queue like this:

```python
class Stack(deque):
    def popleft(self):
        return self.pop()

kqueue = Stack
```
This single change caused some tests to fail and some tests to even hang indefinitely.
Here is an example output for the [test_event_get_wait](https://github.com/dabeaz/curio/blob/master/tests/test_sync.py#L14):

```
E       assert ['sleep', 'wa...e', True, ...] == ['wait_start',...e', True, ...]
E         At index 0 diff: 'sleep' != 'wait_start'
E         Full diff:
E         - ['sleep', 'wait_start', False, 'event_set', 'wait_done', True, False]
E         ?  ---------
E         + ['wait_start', False, 'sleep', 'event_set', 'wait_done', True, False]
E         ?                      +++++++++

tests/test_sync.py:37: AssertionError
```
I'll try to figure out whether this is related only to the tests relying on the scheduling order or this is something that is inside the kernel.

**Comment by dabeaz** [comment]
If different scheduling policies are implemented, I suspect that they will have to be tested independently of existing unit tests.  Many of the tests do depend on scheduling order (and are in some cases explicitly testing the scheduling).

**Comment by ZhukovAlexander** [comment]
Yeah, I've managed to make some tests pass by relaxing them to only test the desired end result without testing the actual order of execution. Here's and example:

```python

def grouper(n, iterable, fillvalue=None):
    """"grouper(3, 'ABCDEFG', 'x') --> ABC DEF Gxx"""
    args = [iter(iterable)] * n
    return zip_longest(fillvalue=fillvalue, *args)

class TestLock:
    def test_lock_sequence(self, kernel):
        results = []

        async def worker(lck, label):
            async with lck:
                results.append((label, ' acquire'))
                await sleep(0.25)
                results.append((label, ' releasing'))

        workers = [1, 2, 3]

        async def main():
            lck = Lock()
            for i in workers:
                await spawn(worker(lck, i))

        kernel.run(main())

        assert len(results) == 2 * len(workers), "all workers should complete their tasks"

        # each chunk represents a set of actions inside a critical section
        chunks = utils.grouper(2, results)

        # list of sets with unique worker ids per chunk
        ids = [set([i[0] for i in chunk]) for chunk in chunks]

        # check whether each chunk contains only actions from a single
        # worker task, which will prove that at any point in time only
        # one worker was acting in a critical section
        assert all(
            [len(s) == 1 for s in ids]
        ), "only a single worker should act in a critical section"
```
I think this makes test less explicit, but makes it more generic. 

My main point is that it would be nice to have generic tests, so we can play around with different schedulers without writing separate tests for them. I could also add only a subset of tests, that depend on the scheduler, and keep current tests as is.

**Comment by dabeaz** [comment]
Closing for now.  Scheduling order in tests is a tricky issue and I'm not quite sure how to resolve at this time.
