### ISSUE TITLE
Pulling time() function into the kernel

### ISSUE THREAD

**Issue by dabeaz** [dabeaz/curio#92]
The curio kernel uses time.monotonic() internally for its time-related functions.  time.monotonic() is directly used in a few places outside of the kernel (for example, in task.py for timeout related functions).   However, I'm thinking about pulling the clock inside the kernel.    If one thinks of curio as a kind of "mini OS", I think it makes sense for the kernel to be in charge of time.    For example, if one wanted to customize time in some way, it could be done entirely in the kernel and nothing else has to change anywhere else.

This would probably be implemented as a kernel trap.   For example:

    t = await clock()

This would immediately return the value of the current kernel clock.

**Comment by njsmith** [comment]
I think this can be closed.
