### ISSUE TITLE
Is Kernel._crash_handler supposed to be public?

### ISSUE THREAD

**Issue by scribu** [dabeaz/curio#94]
There was a `set_crash_handler()` method at one point, but it's no longer there.

Right now, I'm manually setting the property in order to bubble up errors to py.test:

```python
@pytest.fixture
def kernel():
    kernel = curio.Kernel(log_errors=False)

    def handle_crash(current):
        raise current.exc_info[1]

    kernel._crash_handler = handle_crash

    return kernel
```

**Comment by dabeaz** [comment]
Hmmm. You're right.  There were some changes to the kernel API awhile back and this seems to have been lost.   I'll restore some kind of functionality for this.

**Comment by dabeaz** [comment]
Restored this with a crash_handler keyword argument to the kernel and the run() function.

**Comment by scribu** [comment]
Excellent. Thanks!
