### ISSUE TITLE
Build chat server with curio

### ISSUE THREAD

**Issue by deounix** [dabeaz/curio#95]
I'm trying to make chat server with curio. I want to build this server with TLS/SSL.
My questions :

1. Is curio good for big number of connections ? (Millions)
2. There is many example of chat servers in curio (some uses: tcp and some uses: socket) What should I use ?

The Whole point is : Chat server that accept json packet like : 

{"message": {"from": "from_user@domain.tld", "to": "to_user@domain.tld", "text": "Hi there"}}

Then send it to other users.

Thanks.

**Comment by dabeaz** [comment]
Can curio handle a million connections?  I don't know.  It would depend entirely on whether the Python builtin `selectors` module can handle a million connections.  I'm not aware of  a chat server example and don't have any specific advice on (2).
